### ISSUE TITLE
Centralize Connector Capabilities in a central place

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1006]
In the engines meeting we decided to try to centralize connector capabilities in a central crate. Currently they are scattered over multiple repos.

**Comment by tomhoule** [comment]
They are currently defined in three places:

- [ConnectorCapabilities.scala](https://github.com/prisma/prisma-engines/blob/e8c86b2eed97ef06abd25651f450e957b21f5c31/query-engine/connector-test-kit/src/test/scala/util/ConnectorCapabilities.scala#L7) in connector-test-kit
- [datamodel-connector](https://github.com/prisma/prisma-engines/blob/e8c86b2eed97ef06abd25651f450e957b21f5c31/libs/datamodel/connectors/datamodel-connector/src/lib.rs#L77)
- [test-setup](https://github.com/prisma/prisma-engines/blob/e8c86b2eed97ef06abd25651f450e957b21f5c31/libs/test-setup/src/connectors/capabilities.rs#L4)

From our discussion in the engines meeting, the conclusion was that it is probably possible to merge the two rust ones, but sharing that info with the scala tests seems less easy, so we would probably skip that.

**Comment by tomhoule** [comment]
We now have the connector capabilities in the datamodel connector, I think this issue can be closed.
