### ISSUE TITLE
Introspection Engine: Support constraints and indexes with names that have invalid characters in Javascript

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1038]
This isssue is part of an [epic](https://github.com/prisma/prisma/issues/3193).

**Tasks**
* [x] the underlying name of a constraint/index must be put into the `map` argument instead of `name`
  * [x] for `@@unique`
  * [x] for `@@index`
  * [x] for `@@id`

**Comment by do4gr** [comment]
For @@id the name property is new, while for @@index it goes away. In order to not be breaking we'll need to keep accepting the name property on @@index as well and under the hood pass it into map and also render it back as map in the formatter / during re-introspection.

**Comment by do4gr** [comment]
@relation was missing from the list

This is now implemented.
