### ISSUE TITLE
Migration Engine: Support constraints and indexes with names that have invalid characters in Javascript

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1039]
This isssue is part of an [epic](https://github.com/prisma/prisma/issues/3193).

**Tasks**
* [x] currently the `name` argument is used to determine the underlying name of an index/constraint. `map` must now be used instead if provided.
  * [x] for `@@unique`
  * [x] for `@@index`
  * [x] for `@@id`

**Comment by tomhoule** [comment]
Maybe foreign keys as well?

**Comment by do4gr** [comment]
Yes, there will be a map argument holding the underlying db constraint / index name on @id, @unique, @relation as well. Specifically for SQLServer also for @default.

**Comment by do4gr** [comment]
Apart from @default on SQL server which has it's own issue this is now implemented
