### ISSUE TITLE
Query Engine: Support constraints and indexes with names that have invalid characters in Javascript

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1040]
This isssue is part of an [epic](https://github.com/prisma/prisma/issues/3193).

**Tasks**
* [x] adapt the `DatamodelConverter` to pass through the information about the name argument for `@@id`
* [x] the name of the input field for a compound `@@id` must use the `name` argument if provided instead of our current rule that is based upon the field names

**Comment by do4gr** [comment]
This is now done.
