### ISSUE TITLE
Query Engine: Investigate how we could support union types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1088]
## The idea 
Here is a birds eye view of what we are aiming for with this idea. 
Assume the following Prisma schema:
```prisma
model Post {
    id        Int @id
    viewCount Int
}
```
If the client wants to update the `viewCount` property it has to send a GraphQL query of the following shape:
```graphql
mutation {
    updatePost({
        where: { ... }
        data: {
            viewCount:  {
                set: 1
            }
        }
    })
}
```

This is easy to do if the client calls looks like the following. In this case the shape of the client call and the GraphQL query is the same.
```ts
await prisma.post.update({
  where: {...}
  data: {
    viewCount:  {
      set: 1
    }
  }
});
```

But this annoying for users to type. It is much more intuitive to allow the following syntax additionally. This creates the problem that the client needs to inject `set` key additionally as the underlying GraphQL schema does not support this shape.
```ts
await prisma.post.update({
  where: {...}
  data: {
    viewCount: 1
  }
});
```

So the ultimate goal is to allow the same shape in the GraphQL protocol to lift this responsibility from a Client implementation:
```graphql
mutation {
    updatePost({
        where: { ... }
        data: {
            viewCount: 1                
        }
    })
}
```

This is what we mean by **Union Input Types**. The value for `viewCount` might either be a plain integer or a complex object that can be used to specify more advanced operations (namely our atomic number operations feature).

## IMPORTANT NOTE
This is the first feature that **extends the capabilities of our protocol beyond what's normally possible with GraphQL**. We use GraphQL as the wire protocol between a Prisma Client and the Query Engine for historic reasons. It was an obvious choice for us as we have been using with Prisma 1 and Graphcool already. We know already for a long time that it won't be a good choice at some point anymore. This change is a first sign that we are coming closer to this point.

**Comment by jasonkuhrt** [comment]
This is the RFC for tracking Input union types in GraphQL https://github.com/graphql/graphql-spec/blob/master/rfcs/InputUnion.md. I don't think Prisma should be waiting for this to land (ETA unknown). But I do think it might be of interest to review this design analysis of the feature for anything we can learn from it for Prisma's protocol.
