### ISSUE TITLE
Query Engine: Benchmarking of actual Queries (= look at SQL queries)

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#117]
So far we have done micro benchmarking which allowed us to fix several issues. As a next thing we should figure out if the SQL queries we run are performant. 
Context: @do4gr found out during his bachelor thesis that Prisma 1 is very slow on certain queries. Since we ported the queries almost 1:1 we likely still have those issues.

**Comment by pimeys** [comment]
Test data generator being worked in here https://github.com/prisma/sql-load-test

**Comment by pimeys** [comment]
Currently working on a benchmarker https://github.com/prisma/chihiro/

We store stats to ElasticSearch/Kibana in here https://679bac92601d451f82c75405262a6dff.eu-central-1.aws.cloud.es.io:9243/app/kibana#/visualize?_g=()

**Comment by dpetrick** [comment]
I suggest to rename this issue (or open a new issue/ issues) to be a follow-up task of https://github.com/prisma/prisma-engine/issues/92, which is already dealing with the full benchmark setup. Query performance insights gains from the benchmarking setup should lead to follow-up optimization tasks.

**Comment by divyenduz** [comment]
Internal note: dropping from this sprint

**Comment by yoshuawuyts** [comment]
Note from triage: this has been done!
