### ISSUE TITLE
Send the "server listening" message only after the server has started

### ISSUE THREAD

**Issue by yoshuawuyts** [prisma/prisma-engines#1173]
@timsuchanek reported we were emitting the "server listening" message before the server has started. This requires a retry loop on client to work around. We should fix this in Tide instead by adding a `listen_with` method that invokes a callback _after_ the server has started. I've filed https://github.com/http-rs/tide/issues/712 for that purpose.

**Comment by yoshuawuyts** [comment]
https://github.com/http-rs/tide/pull/724 has been filed which implements `Server::listen_with`. The steps after this are:
- merge and release a tide version with this
- integrate into engines
- remove the retry hack from client

The code for engines should be as easy as:

## After

```rust
    use tide::connection::ConnectionInfo;

    // Create the log message used by `prisma-client` to connect
    let reporter = |info: ConnectionInfo| async move {
        info!("Started http server on {}", info.connection());
        Ok(())
    };

    // Start the Tide server and log the server details.
    if let Some(path) = opts.unix_path() {
        app.listen_with(&*format!("http+unix://{}", path), reporter).await?;
    } else {
        app.listen_with((&*opts.host, opts.port), reporter).await?;
    }
```

## Before
```rust
    // NOTE: This println is essential for the correct working of the client.
    info!("Started http server");

    // Start the Tide server and log the server details.
    // TODO: Tide should have a panicking listen_unix impl.
    if let Some(path) = opts.unix_path() {
        app.listen(&*format!("http+unix://{}", path)).await?;
    } else {
        app.listen((&*opts.host, opts.port)).await?;
    }
```

**Comment by yoshuawuyts** [comment]
Update for the retro: the PR on Tide has not been merged yet, which blocks progress on this. We can carry this over.

**Comment by janpio** [comment]
There are also review comments on the PR that might need work or answers.

**Comment by yoshuawuyts** [comment]
@janpio yes good point; picked that back up again.

**Comment by yoshuawuyts** [comment]
Filed https://github.com/http-rs/tide/pull/740; once that's merged we can pick the patch back up on Prisma's side.
