### ISSUE TITLE
Gate SQL Server from Migration Engine

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-engines#1222]
The first release of SQL Server support will not include the Migration Engine. It works for our tests, but we want to prevent our users from using the migrations due to unknown results that might happen.

We should add a flag to the engine, enabling SQL Server support. And if not enabled, we should return an error.

**Comment by janpio** [comment]
Does this have an issue in prisma/prisma for the Typescript/Client part?

**Comment by pimeys** [comment]
They know about it since yesterday, and accepted my merge.

**Comment by timsuchanek** [comment]
Yep, I'm integrating this now, will update you here when it's done.
