### ISSUE TITLE
Validator should disallow native type Text in combination with unique attribute for MySQL

### ISSUE THREAD

**Issue by carmenberndt** [prisma/prisma-engines#1227]
The following should be illegal on MySQL: 
`field String @mydb.Text @unique`
The reason is that for the text type you can’t have a unique constraint in MySQL. (https://stackoverflow.com/questions/14033378/make-text-column-as-unique-key)

**Comment by tomhoule** [comment]
I don't know if this belongs here or in a separate issue, but on MySQL, `TEXT` columns also [cannot have a default](https://dev.mysql.com/doc/refman/5.7/en/blob.html) at the database level. We may still want to allow defaults since they can be enforced by the query engine, so it's maybe more of a product question.

**Comment by carmenberndt** [comment]
> I don't know if this belongs here or in a separate issue, but on MySQL, `TEXT` columns also [cannot have a default](https://dev.mysql.com/doc/refman/5.7/en/blob.html) at the database level. We may still want to allow defaults since they can be enforced by the query engine, so it's maybe more of a product question.

Maybe open up a separate issue for this, since it's not clear or more of a product question.

**Comment by tomhoule** [comment]
Issue created there for product: https://github.com/prisma/prisma-engines/issues/1244

**Comment by carmenberndt** [comment]
Info: This applies to all `Text` and `Blob` types on MySQL.

**Comment by Fi1osof** [comment]
> The reason is that for the text type you can’t have a unique constraint in MySQL.

Can not **without a key length**. This OK: 

```sql
ALTER TABLE `Resource`
  ADD UNIQUE KEY `uri_UNIQUE` (`uri`(191))
```

**Comment by tomhoule** [comment]
Yes, this is on our radar. Richer index configuration in the schema language is something we will work on at some point.

**Comment by Fi1osof** [comment]
> Yes, this is on our radar. Richer index configuration in the schema language is something we will work on at some point.

Cool! Will wait. Thanks!
