### ISSUE TITLE
Research: Understand compatibility of native types with PSL features

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1246]
**What?**
We need to understand which features of PSL are compatible with the native types we are going to support.

We need to look into compatibility with the following attributes:
* `@id`
* `@default`
* `@unique` + `@@unique`
* `@@index`

An example for an incompatibility is MySQLs native type `TEXT`. You can't declare a column of this type unique.

A good deliverable would be a table in Notion listing all the native types and their compability. Maybe checkmarks and additional explanation if reasons are complicated :-) 

**Why?**
We need to understand this to implement the results of this research in our parser validation.

**Comment by carmenberndt** [comment]
internal notion doc: https://www.notion.so/prismaio/Compatibilities-with-Prisma-attributes-6e0902265bc94b8f88ccb47d780fcccb (ongoing)
