### ISSUE TITLE
MySQL: `TinyInt` must be compatible with `Int` and `Boolean` scalar types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1257]
Currently we allow `TinyInt` only to be used on fields of type `Boolean`. This is problematic for introspection CI and hence we want to lift that restriction and also allow it for `Int`.

**Goal**:
The following schema should be valid.

```prisma
model Blog {
  id    Int     @id
  anInt Int     @db.TinyInt
  aBool Boolean @db.TinyInt
}
```

**SQL Mapping Rules:**
* `Int @db.TinyInt` is mapped to `tinyint` in the database without display width.
* `Boolean @db.TinyInt` is mapped to `tinyint(1)` in the database.

**Steps:**
- [x] allow this schema in the parser
- [x] adapt introspection engine to adhere to SQL mapping rules
- [ ] adapt migration engine to adhere to SQL mapping rules

**Comment by do4gr** [comment]
The introspection engine will also take the default value into consideration. So `column tinting(1) Default 5` will still be an Int.

**Comment by mavilein** [comment]
The only outstanding part is the work in the ME.

**Comment by FredericEspiau** [comment]
This is no longer part of `2.11.0` ?

**Comment by mavilein** [comment]
The work is done in `prisma introspect`, the schema parser and the Prisma Client. Only work left is `prisma migrate` where we will tackle this at a later point.

**Comment by tomhoule** [comment]
This has been fixed by the native types work.
