### ISSUE TITLE
Introduce support for scalar type `BigInt`

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1284]
We decided to introduce the scalar type `BigInt`.
So that means that the following schema is not valid anymore:
```
model Blog {
  id     Int @id
  bigInt Int @mydb.BigInt
}
```
Instead users will have to write it like this:
```
model Blog {
  id     Int    @id
  bigInt BigInt
}
```

**Comment by carmenberndt** [comment]
This will need to be feature gates as well as Decimal and Bytes. Related https://github.com/prisma/prisma-engines/issues/1318

**Comment by do4gr** [comment]
This is merged now
