### ISSUE TITLE
Implement default mapping for the scalar types `Bytes`

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1286]
We that the default mapping for `Bytes` should be:
* `bytea` on Postgres
* `longblob` on MySQL

**Comment by mavilein** [comment]
Postgres is probably already correct. MySQL is currently `mediumblob` and needs to change.
This is only work in the ME.

**Comment by jknight** [comment]
Not sure this is working? I logged my results at:
https://github.com/prisma/prisma/issues/4107
