### ISSUE TITLE
Datamodel Parser: Implement Errors Spec

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#129]
This work package is part of this [epic](https://github.com/prisma/prisma-engine/issues/128).

Please supply a task list in a comment.

**Comment by tomhoule** [comment]
Note: the schema parser returns a list of errors, but the error spec assumes only one error. https://github.com/prisma/specs/tree/master/errors#p5000-schema-parsing-failed

This is not a problem for displaying, but we now want to return the errors as JSON (to include metadata and error code), so we need to coordinate on a JSON shape for multiple errors.

**Comment by yoshuawuyts** [comment]
Note from triage: we're already covering this.
