### ISSUE TITLE
Native Type Precisions

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engines#1291]
There are four main types of precision for the different native types across MySQL and Postgres (for MsSQL I don't know).

- character max length
- numeric precision
- numeric scale
- time precision

Since there is also the `max` option on MsSQL the parser needs to support optionality on some of the args as well as enum values. 

Currently the parser requires that character_max_length is specified in the datamodel for applicable types. 
This is a requirement on MySQL since you could not create `column varchar` instead you need to specify `column varchar(20)` for example. 
On Postgres on the other hand both are valid, with the absence meaning no limit at all. 

Numeric precision and numeric scale are mostly used for decimal/numeric types, and here the behavior is different as well. Currently the parser always requires the precision definition. 
On MySQL you can create a `column decimal` without specifying both but then precision and scale will be defaulted to (10,0) which is what introspection will get back from the information schema. 
On Postgres you can also omit both but then the describer will return no values at all since there is no default. 

For time the parser already allows for optionality and here the behavior is fine I think. 

Even after the parser is adjusted we will have inconsistencies with reintrospection though. A mysql `field Float @db.decimal` would be reintrospected back as `field Float @db.decimal(10,0)` while the same on Postgres would return an unchanged `field Float @db.decimal`. I think this behavior is correct though since the MySQL column will have a constrained precision specified by the defaults whereas Postgres won't. 

Some of these precisions also have range restrictions depending on the db/underlying datatype. Should the parser also implement these? So rejecting:
- decimal(66,6)
- bit(65) on MySQL
- etc..

**Comment by do4gr** [comment]
Not implementing at least the optionality in the Parser is not an option imo. On Postgres there is no default I could specify for varchar or decimal without precision. So currently schemas get correctly introspected and rendered without precision in these cases, but the parser then rejects these datamodels.

**Comment by carmenberndt** [comment]
This is already done. `VarChar` and `Char` are optional on Postgres and the range validations are also implemented.
