### ISSUE TITLE
Fail CI if the rust build emits any warnings

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#1384]
We should fail our builds on CI if a warnings is emitted during the build. There's an env var for cargo to accomplish that.

**Comment by yoshuawuyts** [comment]
First PR here: https://github.com/prisma/engineer/pull/34

**Comment by yoshuawuyts** [comment]
Second PR was merged here https://github.com/prisma/prisma-engines/pull/1454, closing this PR.
