### ISSUE TITLE
FindMany with empty `every { OR: [] }` filter should return nothing

### ISSUE THREAD

**Issue by yoshuawuyts** [prisma/prisma-engines#1410]
While authoring https://github.com/prisma/prisma-engines/pull/1371 I found what seems to be a bug. Given the following query:

```javascript
prisma.myTable.findMany({
    where: {
        Tracks: {
            every: {
                OR: [],
            }
        }
    },
});
```
We would expect that since no filter is defined, no filter matches, and thus we return no items:

```json
{"data":{"albums":[ ]}}
```

Instead we return all items which have no `Tracks` defined:

```json
{"data":{"albums":[ {"Title":"TheAlbumWithoutTracks"} ]}}
```

The tests affected appear to be:

- `"2 level m-relation filters that have subfilters that are connected with an explicit AND" should "work"`  (when #1371 is merged)
- `"2 level m-relation filters that have subfilters that are connected with an explicit OR" should "work"`

**Comment by timsuchanek** [comment]
Already fixed
