### ISSUE TITLE
[EPIC] Move Scala integration tests to Rust

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma-engines#1601]
This is the overarching epic that collects all issues related to moving the central QE integration test suite from Scala to Rust.

With the integration of MongoDB, we will have a lot more Capabilities and test separations / specific feature targets for MongoDB. This would require major work in the Scala test suite to integrate and we're using this opportunity to finally start the effort of moving tests over to be closer (for example) to the connector capability definition without needing to duplicate them in Scala.

This is WIP at the moment, concrete breakdown and plan of implementation will follow.

**Comment by matthewmueller** [comment]
Can we close this one? :-)
