### ISSUE TITLE
Reduce the size of Query Engine by cutting the amount of runtimes

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-engines#1726]
We don't really need async-std AND tokio. Cutting one of them out would reduce the binary size about 5MB+. This requires changing the http server and possibly also fixing tiberius TLS so it uses tokio when on tokio runtime and async-std if not.

There is a PR later in the comments to switch from Tide to Hyper http server. If possible, get rid of the unix domain socket support to cut down in size. Try to run our test suite on top of the http server to be sure nothing breaks.

**Comment by Jolg42** [comment]
We should do this too in TS tests https://github.com/prisma/prisma/issues/6088 (it's easy to add)

**Comment by pimeys** [comment]
Yeah. Although this one is hopefully soon not needed anymore due to napi...

**Comment by garrensmith** [comment]
PR for this is https://github.com/prisma/prisma-engines/pull/2090
This would need to be updated.

**Comment by matthewmueller** [comment]
Next steps: 

- Figure out if the binary is the only place async_std is used? Does Tiberius used async_std?
- If it's only the binary, it's less important since Node-API is the default now.

If we include the dependency in Node-API, this would be a nice win.

**Comment by garrensmith** [comment]
This work is done. We have removed async-std with tokio.

**Comment by Jolg42** [comment]
@garrensmith do you have an approximate reduction in MB you saw after that?

**Comment by garrensmith** [comment]
I had a quick look this morning and I'm not noticing any size in the query engine which is a surprise. Maybe @pimeys could help with that.
