### ISSUE TITLE
Testdb setup ignores Migrate errors

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engines#1834]
This is hiding a bunch of ddl failures on SQLServer tests. Seems they are all related to Cascade problems. 

<img width="502" alt="Screen Shot 2021-04-09 at 17 22 26" src="https://user-images.githubusercontent.com/16278407/114203311-53fa0c80-9958-11eb-900e-8e178d91ffab.png">

You can trigger the tests by modifying the testdb setup like below. 

```scala
 def resetAndSetupDatabase(): Unit = {
    import scala.sys.process._
    val cmd = List(EnvVars.migrationEngineBinaryPath, "cli", "-d", project.fullDatamodelBase64Encoded, "qe-setup")

    cmd.!  // switch this to cmd.!! to make the tests fail upon migrate errors
  }
```

**Comment by tomhoule** [comment]
Scheduled for this cycle because sql server.
