### ISSUE TITLE
Found bug in migration checksum

### ISSUE THREAD

**Issue by bryanmcgrane** [prisma/prisma-engines#1887]
I noticed there is an issue with the checksum generation code found here:

https://github.com/prisma/prisma-engines/blob/c1113c6285960eb54d71be971738abe600727268/migration-engine/connectors/migration-connector/src/lib.rs#L88

I noticed the issue when inspecting the **_prismia_migration** tables that are generated in my database.

It appears there is an issue with converting from the bytes to a hex string, where 0's are sometimes being stripped out of the final checksum string. It's relatively simple to replicate the issue. Below is an example (apologies in advance, I'm not a Rust developer):

```
/// Prisma checksum
checksum("hello")

/// Result is 2cf24dba5fb0a3e26e83b2ac5b9e29e1b161e5c1fa7425e7343362938b9824
/// Note the length is only 62 characters
```

```
#!/bin/bash
echo -n hello | shasum -a 256

# Result is 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
# Note the length is the correct 64 characters
```

Characters that are missing from Prisma's checksum
2cf24dba5fb0a3`0`e26e83b2ac5b9e29e1b161e5c1fa7425e73`0`43362938b9824

Edit:
I dug a little deeper and I found the issue was with this line where bytes are converted to hex strings.

https://github.com/prisma/prisma-engines/blob/c1113c6285960eb54d71be971738abe600727268/migration-engine/connectors/migration-connector/src/lib.rs#L110

`write!(checksum_string, "{:x}", byte).unwrap();` needs to have a 0 padding built in for bytes with leading 0's.

**Comment by tomhoule** [comment]
Hi @bryanmcgrane! Good catch, thanks for reporting this, I'll look into it asap. We'll have to be careful to still accept the bad checksums for now, unfortunately (while fixing the new ones), or it will break existing users.

**Comment by tomhoule** [comment]
PR is here: https://github.com/prisma/prisma-engines/pull/1889

I think we should merge after next release (Tuesday), since current checksums aren't completely broken, and that will give us some time to test before releasing that change to users.
