### ISSUE TITLE
Error: subquery has too many columns

### ISSUE THREAD

**Issue by darioielardi** [prisma/prisma-engines#1932]
I'll try my best to describe the issue, here you can find a repo with an isolated reproduction case: https://github.com/darioielardi/prisma-subquery-has-too-many-columns.

I'm working on a multi tenant data model, where every model has a `tenantId` field and a unique composite index ( `tenantId`, `id` ), and every foreign key involves the `tenantId`.

Example schema:
```prisma
model Tenant {
  id   String @id @default(cuid())
  name String

  foos Foo[]
  bars Bar[]
}

model Foo {
  id       String @id @default(cuid())
  tenantId String

  bar    Bar?
  tenant Tenant @relation(fields: [tenantId], references: [id])

  @@unique([tenantId, id])
}

model Bar {
  id       String @id @default(cuid())
  fooId    String
  tenantId String

  foo    Foo    @relation(fields: [tenantId, fooId], references: [tenantId, id])
  tenant Tenant @relation(fields: [tenantId], references: [id])

  @@unique([tenantId, id])
}
```

The one-to-one relation between `Foo` and `Bar` is the source of the problem. A `Foo` can be created without a `Bar`, but a `Bar` needs a `Foo`, that's why the relation field is on the `Bar` model. I didn't find a way to make the relation bidirectional ( having a `barId` field on the `Foo` model as well ) without having Prisma yelling at me ( I guess Prisma doesn't support bidirectional relations at all at the moment? ).

That said, if I want to query for all `Foo` rows that do not have a related `Bar`, this is the query according to Prisma docs:
```typescript
const foos = await db.foo.findMany({
    where: {
      bar: {
        is: null,
      },
    },
  });
```

Which, unfortunately, translates to the following SQL query:
```sql
SELECT
  "public"."Foo"."id",
  "public"."Foo"."tenantId"
FROM
  "public"."Foo"
WHERE ("public"."Foo"."id")
NOT IN(
  SELECT
    "public"."Bar"."tenantId", "public"."Bar"."fooId" FROM "public"."Bar"
  WHERE ("public"."Bar"."tenantId" IS NOT NULL
    AND "public"."Bar"."fooId" IS NOT NULL))
OFFSET 0;
``` 

The subquery for the `NOT IN` clause `SELECT`s both the `tenantId` and `fooId` columns, which obviously causes a `subquery has too many columns` error.

Let me know if there's anything more I can do to help with this.

**Comment by darioielardi** [comment]
I actually wanted to open this in the prisma repo, which I'm doing right now. Let me know if you want me to close this or maybe this is actually the right place.

**Comment by janpio** [comment]
Did you already create a copy over there? Otherwise I can also move this @darioielardi

**Comment by darioielardi** [comment]
@janpio I did, but thank you anyway.
https://github.com/prisma/prisma/issues/7072
