### ISSUE TITLE
Remove unnecessary joins

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma-engines#219]
As a remnant of our old approach that had join relation tables for all kinds of relations we are doing unnecessary joins for inlined relations. If you assume a Prisma schema like this:

```groovy
model User{
    id: Int @id 
    name: String
    post: Post
}

model Post{
    id: Int @id 
    title: String
    author: User
}
```

In our current approach for One-To-Many and One-To-One relations we store the related id inline on one of the models and save the join table. But we are still using the logic from when we always had relation tables. 

In order to resolve the following GQL query `users{name, post{id}}` we do a series of SQL queries depending on which side the related id is inlined. 

If it is inlined in the post we do the following:
* fetch the user
* join the post with post to get the related posts

If it is inlined in the user we do the following:
* fetch the user
* join the user and the post to get the related posts
  
Julius already removed the unnecessary join for the first case.

But it is also possible to optimize the second case. We could: 
* fetch the user 
* use the postId that was contained in the user to access the related posts directly without a join. 

This case is a bit more complex code wise, which is why it gets its own issue.

**Comment by pimeys** [comment]
This is still pending for being quite tricky to do.

**Comment by dpetrick** [comment]
This is postponed, potentially after release.

**Comment by divyenduz** [comment]
Internal note: dropping this for now

**Comment by pimeys** [comment]
This was done in AUMFIDARR.
