### ISSUE TITLE
Refactor ConnectorCapability::ForeignKeys to ReferentialIntegrity checks

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma-engines#2396]
## Overview

With the onUpdate emulation merged, there's one last thing to be done:

https://github.com/prisma/prisma-engines/pull/2318#discussion_r746714081

**Comment by tomhoule** [comment]
Since https://github.com/prisma/prisma-engines/pull/2384 is relevant here, if anything seems confusing please get in touch and we can discuss how to approach _configurable_ parameters that affect client behaviour in the schema parser.
