### ISSUE TITLE
[EPIC] Composite API implementation

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma-engines#2511]
**⚠️ This Epic is no longer being updated. We're tracking all items for GA in https://github.com/prisma/prisma/issues/8788**

## Overview
This epic tracks the design and implementation work for the initial composite field API.
Internal design document: https://www.notion.so/prismaio/Embedded-object-API-surface-bfa2b793fcaa4845bdc31c25e45d31cd

### Datamodel
- [x] #2591
- [ ] #2600
- [x] #2605

### Reads
- [x] #2512
- [x] #2674
- [ ] #2514
- [ ] #2675
- [ ] #2676
- [ ] #2677
- [ ] #2678
- [ ] #2679
- [ ] #2680
- [ ] #2681
- [ ] Optional: Implement aggregations on composites. This may require a design pass beforehand.
- [ ] Optional: Implement groupBy.

### Writes
- [x] #2529
- [x] #2530
- [x] #2531
- [x] #2532
- [x] #2533
- [ ] #2534
- [ ] #2535

**Comment by matthewmueller** [comment]
Closing in favor of: https://github.com/prisma/prisma/issues/8788
