### ISSUE TITLE
Kaspersky antivirus detects build files as malicious

### ISSUE THREAD

**Issue by Venryx** [prisma/prisma-engines#2601]
I made a fresh clone of this `prisma-engines` repo, loaded the root folder in VSCode, and soon began getting tons of popups from Kaspersky Antivirus that the `build_script_build-XXX.exe` files had malicious contents: specifically, the `VHO:Trojan.Win32.Agent.gen` and `VHO:Trojan.Win32.Convagent.gen` threats.

These of course are either false positives, or I have something else which is infecting the files (the former seems more likely).

I raise the issue here in case others hit the same issue, to try to collect information on it. (such as what is causing it, and ways to fix it besides just blocking Kaspersky from scanning the whole folder)

Here is a screenshot of some of its detections:
![](https://i.imgur.com/0M9opkB.png)

**Comment by Venryx** [comment]
This seems like a similar bug report relating to build processes (except for C++ and Go rather than Rust, with the latter being invoked from VSCode similar to my case): https://community.kaspersky.com/virus-and-ransomware-related-questions-157/vho-trojan-win32-convagent-gen-detected-when-trying-to-compile-c-codeblocks-17604

**Comment by janpio** [comment]
We had similar reports for our built engine files that we are actually using in Prisma CLI and Client, here is one example: https://github.com/prisma/language-tools/issues/925 + https://github.com/prisma/prisma/issues/10257 Those were mostly/all Cynet doing the detection, but also some McAffee and Sangfor Engine Zero thrown in - and even some Windows Defender.

No previous reports from Kaspersky yet though.

Do you have any report from it when using Prisma CLI and Client with the default engine files we ship with?

What are the exact steps someone would need to take to trigger the detection with `prisma-engines` (I see Windows on the screenshot, VSCode you mentioned, and on the bottom right I see "Kaspersky Security Cloud" - but how would I install that? Is it a private or corporate installation?)?

**Comment by Venryx** [comment]
> Do you have any report from it when using Prisma CLI and Client with the default engine files we ship with?

I am currently only in the "evaluate" phase for the Prisma library, so I don't know whether the default engine files shipped with Prisma have the same issue, unfortunately.

As for reproducing the problem:
* Windows 10
* VSCode: 1.62.3
* rust-analyzer extension: latest
* Kaspersky Security Cloud, free version, private installation (for my personal dev pc): https://www.kaspersky.com/free-cloud-antivirus
* `cargo --version` output: `cargo 1.57.0 (b2e52d7ca 2021-10-21)`

I simply opened the root folder of the repo in VSCode, with the rust-analyzer extension enabled, and as I browsed around (and rust-analyzer did its analysis in the background), I got lots of popups from Kaspersky in the bottom-right of my screen. (on clicking that, the window in the screenshot showed up)

**Comment by janpio** [comment]
Can you maybe upload one of the files here that trigger the detection? If you zip it, you can attach it directly to a comment here. With that we can look at it a bit already while we try to reproduce this. Thanks.

**Comment by Venryx** [comment]
Sure, here is a zip containing two folders whose `build-script-build.exe` files are detected by Kaspersky as malicious:
[KasperskyFiles.zip](https://github.com/prisma/prisma-engines/files/7899712/KasperskyFiles.zip)

I uploaded the zip file to [virustotal.com](https://virustotal.com), and this is the result: https://www.virustotal.com/gui/file/419f97595a76435b7a3c61bb03dbc124431985aa858bc09d7cc77fee6f7c2113

And here is a second upload with just the two exe's: https://www.virustotal.com/gui/file/9775d0785885a1aa3da3545ac12986dfbe14fa220b3991657bc8d7d3a40bd834

The good news is that the Kaspersky detection was replicated by virus-total (for both zips), so those exes are definitely the right ones.

I suppose the long-term solution is to file a report with Kaspersky getting them to stop detecting these files as malicious; I don't have the energy to do that atm though. (For now I am working around the issue by adding exceptions to Kaspersky.)

**Comment by janpio** [comment]
Thanks, uploading to VirusTotal would have indeed been one of the next steps. 
Kaspersky's own tool interestingly does not detect the file as a threat: https://opentip.kaspersky.com/419F97595A76435B7A3C61BB03DBC124431985AA858BC09D7CC77FEE6F7C2113/

Same results for the actual `.exe` files extracted from the archive, no detection on opentip but both detected on virustotal: https://www.virustotal.com/gui/file/f3ebb9712c409d7d7703403a36fec055cefbee224aef643d8a020b85a1fca8bb?nocache=1 https://www.virustotal.com/gui/file/b2f666177760bc1542cf84d5dedf8cebf9359c84eee830f1bc99f0b6b4a185bd?nocache=1 - Interesting here is that both files are also detected by Cynet, that other anti virus provider that is always detecting our actual engine files as threads for no reason, additionally to Kaspersky.

**Comment by pantharshit00** [comment]
Hello @Venryx 

I just span up Windows VM with Kaspersky to try this out and looks like Rust `1.57` is generating these artifacts which are being flagged by the Kaspersky system which I wasn't able to reproduce with Rust `1.58`. Can you please also try this once with that version? You might get a collision in file names while building which is known issue on Windows so you might need to run `cargo build` twice.

**Comment by Venryx** [comment]
Indeed; I updated Rust to v1.58, removed the Kaspersky exceptions, re-opened VSCode, then ran `cargo build` three times, and did not hit any errors. :)

As far as I can tell, the issue is resolved with v1.58 (hence closing); it's too bad I happened to installed Rust just prior to v1.58, but oh well!

Thanks for your help.

**Comment by Venryx** [comment]
Hmm. While the issue is not showing up in the `prisma-engines` repository anymore (so far anyway), it *is* still showing up for the [async-graphql](https://github.com/async-graphql/async-graphql) library.

I suppose this is not a pressing concern for the `prisma-engines` repository now, but I figured I would mention it. There must be something about the details of the Rust compiler's output that causes it to pattern-match with Kaspersky's detection for certain codebases. Updating to v1.58 must have subtly tweaked the compiler output such that the pattern no longer matches for `prisma-engines`, but still does for `async-graphql`.

Anyway, since Kaspersky is the only (well, one of two) antivirus software that has these false-positives, I expect that it will be resolved "upstream" by Kaspersky in the near future, making further debugging unnecessary.

Rather than raising a new issue in the `async-graphql` library, I think I will just add my exception back in Kaspersky, and wait a few months. If it still occurs then, I'll re-evaluate; but for now it looks like it'd just be wasted effort on a temporary detection flaw.

**Comment by janpio** [comment]
That is interesting, and of course kinda implies it could also come back to our repo any time. Unfortunately I see no way to really let Kaspersky know as all the files I had and could upload to https://opentip.kaspersky.com/ came back clean - so there is no way to raise an objection :(
