### ISSUE TITLE
[MongoDB] Having filters don't work without selection

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma-engines#2768]
## Overview

The `$group` stage rendering is triggered by the query selection. Therefore, if there isn't a selection, the having filter tries to match against aggregated variables that don't exist.

## Reproduction

```graphql
query {
  groupByTestModel(by: [id], having: { some_field: { _max: { gt: 2 } } }) {
    id
  }
}
```

**Comment by matthewmueller** [comment]
Is this something we want to get fixed before GA?

**Comment by Weakky** [comment]
Yes, I added it to the epic
