### ISSUE TITLE
`prisma-fmt` not writing to file

### ISSUE THREAD

**Issue by princejoogie** [prisma/prisma-engines#2809]
# Info

The `prisma-fmt` binary is able to show the formatted schema in `stdout` but is not reflecting in the `schema.prisma` file. This behavior is the same in the `prisma-fmt` binary included in `node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x`

## Prisma Fmt
```bash
prisma-fmt --version
# prisma-fmt 4c9d4edf238ad9c4a706eb5b7201ee0b4ebee93e
```

## OS
- Windows 11 on WSL2 Ubuntu 20.04

## Reproduction

1. with `prisma-fmt` built from source ❌
![image](https://user-images.githubusercontent.com/47204120/160523058-b682d5be-02b2-4207-b39b-136bd3b302c5.png)

2. with `prisma-fmt` included in `node_modules` ❌
![image](https://user-images.githubusercontent.com/47204120/160523453-bbae79b7-5b14-4fe7-9596-3c5604e5cbd9.png)

3. with `yarn run prisma format` ✔️
![image](https://user-images.githubusercontent.com/47204120/160523539-6b22788a-14f5-4105-8d59-72cf416bf023.png)

**Comment by pimeys** [comment]
Hi @princejoogie. The tool `prisma-fmt` used to be the backend for the `prisma-cli` and for the `language-server` tools to format the prisma schema and give autocompletion for prisma schemas to the editors.

Nowadays we [compile this project to WebAssembly](https://github.com/prisma/prisma-fmt-wasm), and it is quite possible the whole `prisma-fmt` binary will not be available in the near future.

But, to your original question, you can utilize POSIX a bit here and redirect the output to a file:

``` bash
cat test.prisma | prisma-fmt format >foo.prisma
```

The `-o` parameter was never even used with `prisma-fmt` and as you said, it just does not work at all.

Of course now our management will come to tell us that `prisma-fmt` is not the official tool for the job and, well, they are correct. You should be using the `prisma` cli tool and the `prisma format` command instead if you want to go with the official path… And they are kind of right too.

But...

I guess you're looking from some solution outside the node.js ecosystem, like a compiled binary. If you read the sources for `prisma-fmt` you see they use the library in `libs/datamodel/core` for almost all the functionality. We do not guarantee the stability of this API, but I can also say the public API of `datamodel` has not really changed for a long time, and even if it changes, it will be quite minimal. If you want to hack, it's not super hard to write a small tool for yourself that compiles to a single binary. Beware though, that Prisma will not provide support for this, but as a developer I have to say this might be a fun little project!

**Comment by princejoogie** [comment]
@pimeys yep, my main use case why i need the `prisma-fmt` binary is to format prisma files when editing in neovim. I previously had `yarn run prisma format` as the formatter for prisma files but that take a couple of seconds to boot and run. I was able to make `prisma-fmt` work with stdin with [this](https://github.com/princejoogie/dotfiles/commit/3d2c052fd1fbc003ab9cd2214f866a25ad731407) configuration.

if I understood correctly, the `prisma-fmt` has no promised future support and the official formatter used lives inside `libs/datamodel/core`?

**Comment by pimeys** [comment]
Well, you're in luck because the [language-server](https://www.npmjs.com/package/@prisma/language-server) should be able to do that with any language server mode, also in neovim. I haven't been using vim recently, but in Emacs I basically [trigger](https://github.com/pimeys/nixos/blob/main/desktop/emacs/config.org#prisma=) the `lsp-mode`'s formatting before saving the file.

In neovim you should be able to do the same. Let's invite the author of [vim-prisma](https://github.com/pantharshit00/vim-prisma) @pantharshit00 to the discussion. He should know better how to do that. Also @tomhoule might know, he uses neovim too in Prisma.

**Comment by janpio** [comment]
We document the available plugins for Vim/neovim here: https://www.prisma.io/docs/guides/development-environment/editor-setup#vim (which are the ones you mentioned @pimeys and they should just work)
