### ISSUE TITLE
Introspection Engine: Endpoint that returns the full SQL schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#282]
When introspection fails in the validation step that the CLI executes via the Query Engine, we want to report the error and its information to the Error Backend for further analysis.

The model and the errors the CLI already knows, but the underlying SQL schema that was introspected and inferred to the schema is not known. For that reason it would be great if the Introspection Engine could offer an endpoint that returns the schema to the CLI.

**Comment by do4gr** [comment]
We will do two things for this endpoint:

* return the internal SQLSchema description that the SQLSchemaDescriber produces
* additionally fetch the complete contents of information_schema / sqlite_master / pragma

This will hopefully allow us to pinpoint errors in Introspection Engine / SQLSchemaDescriber

**Comment by janpio** [comment]
Internal Note: We will move forward with this if/when we actually have failures that indicate having this would help understanding them. These failures might be reported via the existing Error Reporting.

**Comment by yoshuawuyts** [comment]
Note from triage: there doesn't seem to be any need for this anymore!
