### ISSUE TITLE
Support starting traces in JS

### ISSUE THREAD

**Issue by cprieto** [prisma/prisma-engines#2859]
We need an API surface in the Prisma Client to enable/disable tracing collection. This API should call and pass certain parameters, like:

 - Collector endpoint
 - Traces span name (required for certain collectors like Jaeger)

We need to expose this to clients.

This requires https://github.com/prisma/prisma/issues/11093

**Comment by matthewmueller** [comment]
Does this need to be a public API? I'd personally prefer it remain internal and enabled/disabled depending on if the application itself has been instrumented.
