### ISSUE TITLE
Connector Testkit: Test error codes and messages again

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#288]
We have lots of test cases that check that specific errors are returned by the query engine. During the rewrite we deactivated those since we were not returning proper codes and messages. The expectation passes as long as an arbtitrary error is returned.
Now that the error spec is implemented we should reenable those checks again. It is likely that during this work we discover that lots of errors are missing in the current spec. We will then need to extend it.

**Comment by yoshuawuyts** [comment]
Note from triage: @tomhoule has done this!
