### ISSUE TITLE
prisma-fmt doesn't support tabs

### ISSUE THREAD

**Issue by Arteneko** [prisma/prisma-engines#2895]
It appears prisma-fmt supports spacing but not tabs... Is support planned at some point?

**Comment by janpio** [comment]
Until now we had no feature requests that I am aware of supporting tabs for formatting.

**Comment by cyyynthia** [comment]
> Until now we had no feature requests that I am aware of supporting tabs for formatting.

Then I'll be the 2nd one asking for it! I don't know why spaces are so popular for indentation when they bring 0 advantages compared to tabs, but bring tears and pain for visually impaired people... Indentation with spaces is highly inaccessible!

 - https://www.reddit.com/r/javascript/comments/c8drjo 
 - https://twitter.com/Conundrum9999/status/1617721075747688448

I personally do not understand why the space-based indentation became so popular, when tabs can serve the same purpose and is configurable per-viewer without causing any change to a codebase.

While tabs may not be the "popular choice", I think it'd be beneficial to people with special a11y needs. I assume the "no rules" spirit makes it difficult to call for this kind of change, but I hope to see at least a CLI flag...

**Comment by janpio** [comment]
Then maybe open a feature request for this at https://github.com/prisma/prisma.

(Closing this issue now to signal that this will not lead us to consider this as a feature request)
