### ISSUE TITLE
Many to many parent_id to child_id mapping should rely on coerced values

### ISSUE THREAD

**Issue by JingLi1998** [prisma/prisma-engines#2928]
Currently the query engine is broken for m2m relationships when using `bigint` as the primary key. [Related issue](https://github.com/prisma/prisma/issues/12206)

The culprit seems to be an inconsistent usage of coerced and non-coerced values when inserting and getting values from the `id_map` variable. 

https://github.com/prisma/prisma-engines/blob/55eef363a3b2e17691b1f98ed28da8b387f3bdb8/query-engine/core/src/interpreter/query_interpreters/nested_read.rs#L80-L89

**Comment by Weakky** [comment]
Hey @JingLi1998,

The original issue was closed a while ago and we just realized you had posted a PR for it. Sorry we didn't see your PR earlier 🙏

Please re-open if you think it's still an issue.

Thanks!
