### ISSUE TITLE
Update ARCHITECTURE.md section around transactions and verify state of sql server

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma-engines#2933]
https://github.com/prisma/prisma-engines/blob/main/migration-engine/ARCHITECTURE.md#why-does-migrate-not-run-migrations-in-a-transaction-by-default

But then I saw: https://github.com/prisma/prisma/issues/7641

and wondered what the truth is

**Comment by janpio** [comment]
Internal discussion: https://prisma-company.slack.com/archives/C02FNFLDUS3/p1653921935947449?thread_ts=1653405958.272039&cid=C02FNFLDUS3
