### ISSUE TITLE
Migration Engine: Loosen id requirement. At least one unique criteria is enough.

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#295]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/292) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by tomhoule** [comment]
https://github.com/prisma/prisma-engines/pull/478 will make it valid in the schema parser and enable work on the migration engine

**Comment by tomhoule** [comment]
Work should be unblocked on this now.

**Comment by tomhoule** [comment]
PR: https://github.com/prisma/prisma-engines/pull/505

**Comment by tomhoule** [comment]
I think we can consider the initial implementation of this done.
