### ISSUE TITLE
EPIC: Native Types

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#30]
**Product Epic**: The corresponding product epic can be found [here](https://github.com/prisma/prisma/issues/3447).

**Description**: The Prisma Schema Language allows the user to define custom types that should be used for a given field.

**Example**:
The following example shows a `User` model where the combination of `firstName` and is backed by a varchar column.
```graphql
datasource pg1 { 
  .. 
}

model User {
  id        String @default(cuid())
  firstName String @pg1.varchar(123)
  lastName  String
}
```
## Links to actual Work Packages
* [Datamodel Parser](https://github.com/prisma/prisma-engine/issues/71)
* [Migration Engine](https://github.com/prisma/prisma-engine/issues/72)
* [Query Engine](https://github.com/prisma/prisma-engine/issues/73)
* [Introspection Engine](https://github.com/prisma/prisma-engine/issues/74)
* [Language Tools](https://github.com/prisma/language-tools/issues/384)

**Comment by mavilein** [comment]
## Initial break down of Work Packages
* general
  * map out all custom types of the supported databases. Map them to Prisma Core primitive types.
* Datamodel Parser
  * extend `Field` data structure in `dml` module to store informations on custom types
  * implement new `DirectiveValidator` for custom types that must be part of the Datasource interface
  * test cases:
    * basic happy path
    * use invalid type for a database type
* Migration Engine
  * core: implement new algorithm to diff custom directives. This will require us to rewrite the complete diffing logic. This will diff the `ast` than the `dml` data structures. This will lead to a breaking change of the structure of the `steps.json`.
  * sql connector:
    * calculation of sql schema
    * diffing of sql schemas
    * add SQL rendering to database step applier
* Query Engine
  * We probably need to implement some kind of value coercion here. This is needed to e.g. coerce the value of a field like `field String @pg.json` from the underyling json type to String.
  * This will require significant work for the `InternalDatamodel` and the `DatamodelConverter`. We will have to work on bringing the `InternalDatamodel` and the `dml::Datamodel` closer together.
* Introspection Engine:
    * core: no work required
    * connector:
        * verify that the `sql-schema-describer` can handle compound custom types
        * adapt Datamodel calculation so that custom types are put into the model

**Comment by mavilein** [comment]
I have asked for clarification of the spec: https://github.com/prisma/specs/issues/173

**Comment by do4gr** [comment]
Native types got stabilized in 2.17!

**Comment by Jolg42** [comment]
See https://github.com/prisma/prisma/releases/tag/2.17.0
