### ISSUE TITLE
Migration Engine: @relation(references: ..) for multiple fields

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#303]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/301) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by tomhoule** [comment]
I started working on this.

**Comment by tomhoule** [comment]
This was implemented in https://github.com/prisma/prisma-engine/pull/334

**Comment by tomhoule** [comment]
Most of the support is already merged. I am waiting on `user User @relation(references: [id, name]) @@map(["user_id", "user_name"])` (the `@map` part) support to land in the parser to test it and close this issue.

**Comment by mavilein** [comment]
@tomhoule : the `@map` part is available on master now

**Comment by tomhoule** [comment]
This is implemented and tested. See the tests in migration_tests.rs, starting with `relations_can_reference_multiple_fields` for examples.

**Comment by tomhoule** [comment]
@dpetrick we were talking about it this morning, I re-checked and it is indeed already implemented. There still remains the explicit relation side problem, which is being dealt with in https://github.com/prisma/prisma-engines/pull/433 afaik.
