### ISSUE TITLE
Where do i download the binaries?

### ISSUE THREAD

**Issue by mwitteveen** [prisma/prisma-engines#3130]
I am a little bit confused where to download the binaries? Or can I only build them? 

At the moment I am on a mac machine amd64 and I need to setup the binaries to be used inside a cicd pipeline and thus the binaries are not present on my own machine (the paths present in prisma --version command).

The docs do not mention where to download them. I pulled the repo but that one is 700+ mb and thats quite heavy to add to a pipeline setup script. 

The binaries have to be downloaded from somewhere by the client so where are these paths documented?

@update:
Can I install @prisma/engines package and use those paths? That should be the documented way to setup a restricted no internet access environment.

**Comment by medz** [comment]
https://github.com/odroe/prisma-dart/blob/main/bin/src/binary_engine/binary_engine.dart#L118
https://github.com/odroe/prisma-dart/blob/main/lib/src/configure/environment.dart#L47

Here is an example of downloading a binary engine.

URL format ：
```
https://binaries.prisma.sh/all_commits/{version}/{platform}/[query| migration|introspection]-engine.[gz|exe.gz]
```

https://github.com/odroe/prisma-dart/blob/main/packages/prisma_get_platform/lib/src/get_binary_platform.dart Here is a list of platforms.

**Comment by medz** [comment]
In fact, reading the source code of Prisma ORM JS/TS client can fully understand where to download the binary query engine.
