### ISSUE TITLE
Why? Request transaction APIs always 404

### ISSUE THREAD

**Issue by medz** [prisma/prisma-engines#3163]
I'm having issues developing with the Prisma Query binary engine, requests to query-engine's transaction APIs always return 404s.

APIs:
- `/transaction/start`
- `/transaction/${id}/commit`
- `/transaction/${id}/rollback`

Maybe it's my problem, but I do a GraphQL request via `/` and it's all successful.

My code: https://github.com/odroe/prisma-dart/blob/main/lib/src/query_engine/binary/binary_engine_io.dart#L343

my standard：https://github.com/prisma/prisma/blob/main/packages/engine-core/src/binary/BinaryEngine.ts#L1033

I found no difference by comparing all the details of the startup parameters, but the request returned 404

Simplest steps to reproduce：

1. `git clone https://github.com/odroe/prisma-dart`
2. `cd prisma-dart/example`
3. `dart pub get`
4. `dart run bin/example.dart`

Console log:
```dart
Transaction start failed.
```

Normally, a transaction object should be returned

**Comment by janpio** [comment]
Without having a look at your code: Did you include all the same headers as the JS/TS version?

**Comment by medz** [comment]
> Without having a look at your code: Did you include all the same headers as the JS/TS version?

Yes, http headers are also consistent

**Comment by medz** [comment]
@janpio My headers: https://github.com/odroe/prisma-dart/blob/main/lib/src/query_engine/binary/binary_engine_io.dart#L337

TS/JS headers: https://github.com/prisma/prisma/blob/main/packages/engine-core/src/binary/Connection.ts#L89

**Comment by medz** [comment]
> Next total guess: Might this be related to a preview feature being enabled or not?

@janpio I'm guessing yes, but the `query-engine` flags don't have any help for enabling the preview feature.

I also did not find the code to pass the preview function flags to the binary query engine in the code of Prisma TS/JS client.

I found through deep analysis of the Prisma JS/TS client code that the current transaction uses the `requestBatch` method.

I'm guessing that independent transaction enablement is a preview feature (found at https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide#interactive-transactions-in-preview) but Dart does not support union types. For a better experience, I have to implement interactive transaction.

I've been looking for code about the binary engine passing preview parameters for almost three hours.

The following is the help information output by the binary query engine, which does not pass the parameters of the preview function:
````
query-engine bcc34eccb8bd811bcf624288e5e05b7abda86699

USAGE:
    query-engine [FLAGS] [OPTIONS] [SUBCOMMAND]

FLAGS:
    -d, --debug Enables server debug features
    -m, --enable-metrics Enables the metrics endpoints
        --enable-open-telemetry Enable OpenTelemetry streaming from requests
    -g, --enable-playground Enables the GraphQL playground
    -r, --enable-raw-queries Enables raw SQL queries with executeRaw/queryRaw mutation
    -h, --help Prints help information
    -o, --log-queries Enable query logging [env: LOG_QUERIES=y]
    -V, --version Prints version information

OPTIONS:
        --datamodel <datamodel> Base64 encoded Prisma datamodel [env: PRISMA_DML=]
        --datamodel-path <datamodel-path> Path to the Prisma datamodel file [env: PRISMA_DML_PATH=]
    -H, --host <host>
            The hostname or IP the query engine should bind to [default: 127.0.0.1]

        --log-format <log-format> Set the log format [env: RUST_LOG_FORMAT=]
        --open-telemetry-endpoint <open-telemetry-endpoint>
            The url to the OpenTelemetry collector. Enabling this will send the OpenTelemtry tracing to a collector and
            not via our custom stdout tracer [default: ]
        --overwrite-datasources <overwrite-datasources>
            Base64 encoded datasource urls, overwriting the ones in the schema [env: OVERWRITE_DATASOURCES=]

    -p, --port <port> The port the query engine should bind to [default: 4466]
    -u, --unix-path <unix-path> The unix socket path to listen on [env: UNIX_PATH=]

SUBCOMMANDS:
    cli Doesn't start a server, but allows running specific commands against Prisma
    help Prints this message or the help of the given subcommand(s)
````

**Comment by tomhoule** [comment]
fwiw the preview features are taken from the generator block in the prisma schema you use to start the query engine, I think.

**Comment by medz** [comment]
> https://github.com/prisma/prisma/blob/main/packages/engine-core/src/binary/BinaryEngine.ts#L1033

Oh my God! I actually forgot about this! I'll test it right away. . . I've been crazy about developing Prisma ORM for Dart these days 😂

**Comment by medz** [comment]
@janpio Indeed

**Comment by janpio** [comment]
Yay 🚀
