### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'InternalDataModel does not exist anymore. Parent internal_data_model is deleted without deleting the child internal_data_model.', query-engine/prisma-models/src/model.rs:102:14

### ISSUE THREAD

**Issue by auser** [prisma/prisma-engines#3376]
We’re seeing a really weird error when running our tests with vitest.

With some debugging, we’re getting this rust error on one of our models (but which one is a mystery:

thread 'tokio-runtime-worker' panicked at 'InternalDataModel does not exist anymore. Parent internal_data_model is deleted without deleting the child internal_data_model.', query-engine/prisma-models/src/model.rs:102:14

It looks like it comes from the model.rs file here: https://github.com/prisma/prisma-engines/blob/9907684a5845cbb6a7aa712fa21fe75455b9b6f6/query-engine/prisma-models/src/model.rs#L80

Not quite certain when the internal_data_model gets dropped. Any debugging tips would be really helpful.

**Comment by auser** [comment]
@janpio I'm not writing a prisma-engine, although I explored that idea.

I'm testing a pretty complex relational application with lots of relationships/edges written on remix (of remix.dev).

**Comment by janpio** [comment]
Can you please open an issue on https://github.com/prisma/prisma/issues/ instead and provide all the information the bug issue template asks for? Then we can debug this hopefully. Thanks.

**Comment by dudeisbrendan03** [comment]
@auser Did you make an issue over on prisma/prisma, having the same issue out of the blue!
```
POST /user (λ: user)
✖ [504] - Lambda timeout.
thread 'tokio-runtime-worker' panicked at 'InternalDataModel does not exist anymore. Parent internal_data_model is deleted without deleting the child internal_data_model.', query-engine/prisma-models/src/model.rs:102:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    13382 IOT instruction  /usr/bin/env NODE_ENV=development    ./node_modules/.bin/sls offline start  
Waiting for the debugger to disconnect...                                                                                                                                                             
Waiting for the debugger to disconnect...
```
