### ISSUE TITLE
Introspection fail with sql connector with particular enum value

### ISSUE THREAD

**Issue by Killian-G** [prisma/prisma-engines#3546]
Hi, I have some problems with the introspection engine when I have a table with a column that contains an enum with an apostrophe and if this enum value is the default, I got a Rust error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', introspection-engine/connectors/sql-introspection-connector/src/pair/default.rs:76:22
```

To reproduce this error, you need just a database with this table:

```sql
CREATE TABLE table_with_enum
(
    enum_column ENUM('don''t know') DEFAULT 'don''t know' NOT NULL
);
```

I have tried to introspect on the commit tagged `4.8.0` and the latest commit on the `main` branch and the same thing append

---

I have tried to debug what was wrong and I share with you what I found if it can help you. I have added `dbg!` where the program panic and I found that the variable `variant` is `don't know` with one apostrophe but when you get all variants of the enum you found only the value `don''t know` with two apostrophes, so it does not match with `variant` variable

**Comment by janpio** [comment]
Can you create an issue over at `prisma/prisma` please and fill the issue template?
We would at least need to know which database you are using.

**Comment by Killian-G** [comment]
Yes I have already created an issue on `prisma/prisma` after this one, this is the link: https://github.com/prisma/prisma/issues/17047 and it's a MySQL database sorry for this missing detail
