### ISSUE TITLE
doubts about the models in schema.prisma

### ISSUE THREAD

**Issue by cgarrotti** [prisma/prisma-engines#4099]
Hi guys ! 
Do the models necessarily have to be in a single file? (schema.prism)

**Comment by aqrln** [comment]
As of now — yes; see https://github.com/prisma/prisma/issues/2377 for the feature request to support splitting the schema into multiple files.

I understand that as you are opening this issue in the engines repository and not in the main repo, you might be interested in a more nuanced answer on this level on the system. That answer would still right now be yes. The schema does not always necessarily have to be in a file (for the query engine), but even then it still has to be provided as a single string.

I'll convert this issue into a discussion. Please post a comment in the issue linked above if you have any question or suggestions that you'd like to add to the feature request.

**Comment by aqrln** [comment]
Actually I can't convert it into a discussion here, I'd have to transfer it to the main repo first, but then it would lose the context.

I'll go ahead and close it for now, please don't hesitate to leave a comment if there's anything else you'd like to add or ask. Feel free to comment in https://github.com/prisma/prisma/issues/2377 or open a new discussion in the main repo as well.
