### ISSUE TITLE
UUID ID fields cause serialization to fail

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma-engines#441]
Issue surfacing the issue in the client: https://github.com/prisma/prisma-client-js/issues/434.
Underlying problem is that the column type of both relation sides is identical, e.g. TEXT, but we still attempt to parse UUID in some code places, and attach the UUID type subsequently.
This causes the rows to mismatch in types, which means that a lookup on the mapping tables from parent id to record fails.

Example schema (snippet):
```
model Asset {
  id          String      @default(uuid()) @id
  owner       User
}

model User {
  id        String    @default(uuid()) @id
  assets    Asset[]
}
```
The db (SQLite) correctly returns TEXT:
```
[query-engine/connectors/sql-query-connector/src/row.rs:34] &self = ResultRow {
    columns: [
        ...
        "owner",
    ],
    values: [
        ...
        Text(
            "6b610e01-1ca1-4d1c-a884-85d06e1355f0",
        ),
    ],
}
```

After transformation, the ID is detected as UUID, which leads to the following mapping:
```
[query-engine/core/src/response_ir/internal.rs:208] &items_with_parent = {
    "owner": {
        Some(
            UUID(
                8df812c6-8efb-44f1-bfba-ef43bfaa33e8,
            ),
        ): Ref(
            Map(
                {
                    ...
                    "id": Value(
                        String(
                            "6b610e01-1ca1-4d1c-a884-85d06e1355f0",
                        ),
                    ),
                },
            ),
        ),
    },
}
```

Note that not all UUIDs are not transformed.

When we try to access the above map, the following is used:
```
[query-engine/core/src/response_ir/internal.rs:207] record_id = Some(
    String(
        "8df812c6-8efb-44f1-bfba-ef43bfaa33e8",
    ),
)
```

The type mismatch makes the child inaccessible and the serialization bails out as the field is required.

**Comment by dpetrick** [comment]
Additional note: This is already fixed on the larger rework of the internals I'm working on as the use of `GraphqlId` is eliminated, which is the root cause of this problems.

**Comment by timsuchanek** [comment]
Fixing this might even fix https://github.com/prisma/prisma-client-js/issues/456

**Comment by dpetrick** [comment]
I believe this is not related, as the issue you mention requires an explicit type coercion based on the foreign key types and direction we're querying. While the code paths end in the same issue, the root causes are different.

**Comment by dpetrick** [comment]
After skimming the code a bit more, it seems feasible to just completely remove the UUID parsing and `GraphqlId::UUID` type and be done with it as a bridging solution until the major reworks hit master.

**Comment by timsuchanek** [comment]
Sounds good!
Just for completeness, this is the error message I get for the UUID error:
`Application logic invariant error: received null value for field owner which may not be null in query-engine/core/src/response_ir/internal.rs:227:26`

**Comment by mavilein** [comment]
The big refactoring is merged now. I validated that UUID is working again properly.
