### ISSUE TITLE
Rename repository to `prisma-engines`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#446]
To clean up a bit, we want to rename this repository to `prisma-engines`. As CI etc might depend on the name, this is tracked in an issue instead of just done.

**Comment by dpetrick** [comment]
Why not `prisma/engines`? We were always at odds with the double Prisma, we can change that now if we want.

**Comment by janpio** [comment]
Good point! Will bring that up in a meeting later today.

**Comment by janpio** [comment]
Decision: Right now most of them start with `prisma-` or `prisma2-`, so we are going to keep this `prisma/prisma-engines` for now.
