### ISSUE TITLE
[DA] Planetscale engine tests: setDefault ref action

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4472]
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:
 
```
new::ref_actions::on_delete::set_default::one2many_opt::delete_parent
new::ref_actions::on_delete::set_default::one2many_opt::delete_parent_no_exist_fail
new::ref_actions::on_delete::set_default::one2many_req::delete_parent
new::ref_actions::on_delete::set_default::one2many_req::delete_parent_no_exist_fail
new::ref_actions::on_delete::set_default::one2one_opt::delete_parent
new::ref_actions::on_delete::set_default::one2one_opt::delete_parent_no_exist_fail
new::ref_actions::on_delete::set_default::one2one_req::delete_parent
new::ref_actions::on_delete::set_default::one2one_req::delete_parent_no_exist_fail
```

Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment]
The test cases above are expected to fail, as:
> MySQL doesn't support SetDefault for InnoDB (which is our only supported engine at the moment).

(the statement above can be found [here](https://github.com/prisma/prisma-engines/blob/dcb8cb9817af92fefaf0f95117dfb5dc19545a2c/query-engine/connector-test-kit-rs/query-engine-tests/tests/new/ref_actions/on_delete/set_default.rs#L1)).

I hence recommend we close this issue.

**Comment by miguelff** [comment]
Agreed @jkomyno. Thanks for evaluating this.
