### ISSUE TITLE
[DA] Planetscale engine tests: tx batch

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4474]
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:
 
- [x] queries::batch::transactional_batch::transactional::one_query
- [x] queries::batch::transactional_batch::transactional::one_success_one_fail
- [ ] queries::batch::transactional_batch::transactional::valid_isolation_level
```


Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment]
I've updated the list of failing tests above as two got fixed in https://github.com/prisma/prisma-engines/pull/4738.
For the remaining test failure, I suggest we deprecate this issue in favor of https://github.com/prisma/team-orm/issues/973, as it contains more detailed information therein.

**Comment by miguelff** [comment]
Superseded by https://github.com/prisma/team-orm/issues/973
