### ISSUE TITLE
[DA] Planetscale engine tests: search filtering

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4476]
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:
 
``` 
queries::filters::search_filter::search_filter_with_index::throws_error_on_missing_index
```

Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment]
Closed via https://github.com/prisma/prisma-engines/pull/4738.
