### ISSUE TITLE
[DA] Planetscale engine tests: oids

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4479]
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:
 
```
writes::ids::byoid::byoid::create_and_return_item_woi_1
writes::ids::byoid::byoid::create_and_return_item_woi_2
writes::ids::byoid::byoid::nested_create_return_item_woi_1
writes::ids::byoid::byoid::nested_create_return_item_woi_2
```

Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment]
Fixed via https://github.com/prisma/prisma-engines/pull/4738.
