### ISSUE TITLE
[DA] Planetscale engine tests: apply_number_ops

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4485]
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:
 
```
writes::top_level_mutations::update_many::update_many::apply_number_ops_for_float
writes::top_level_mutations::update_many::update_many::apply_number_ops_for_int
```

Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment]
Fixed by https://github.com/prisma/prisma-engines/pull/4909.
