### ISSUE TITLE
[DA] Planetscale engine tests: upsert_fails_if_filter_dont_match

### ISSUE THREAD

**Issue by miguelff** [prisma/prisma-engines#4486]
This is a subcluster of failures after having enabled planetscale tests in https://github.com/prisma/prisma-engines/pull/4423
 
 
Failing tests in this cluster:

```
writes::top_level_mutations::upsert::upsert::upsert_fails_if_filter_dont_match
```

Please follow [this process](https://prismaio.notion.site/Process-for-tackling-Planetscale-failing-tests-75e280e923e64e2aadf9e367a42aef8b)

**Comment by jkomyno** [comment]
Fixed via https://github.com/prisma/prisma-engines/pull/4738.
