### ISSUE TITLE
Avoid regex crate for wasm bundle size (to keep cloudflare free plan)

### ISSUE THREAD

**Issue by mizchi** [prisma/prisma-engines#5008]
[This PR](https://github.com/prisma/prisma-engines/pull/5002) significantly increases the prisma-engine wasm build and makes it impossible to build with the free Cloudflare Workers plan!

![image](https://github.com/user-attachments/assets/a4531b20-5dff-4ba6-a12e-35aaeac8a213)

over 1M (cloudflare limit) for pogtgress

https://github.com/prisma/prisma-engines/pull/5002#issuecomment-2367822340

## Problem

In fact, regex crate is getting into the runtime on this line

https://github.com/prisma/prisma-engines/pull/5002/files#diff-7a3b1196bc58de119ae8a5d92271b4749892576c8a8548394ce5e17ca9019186R1-R37

I have done some preliminary research on this and it is +650k if you bundle rust regex crate with wasm.

(these are my notes in Japanese, sry)
https://zenn.dev/mizchi/scraps/413cd989324fc7

## Solution.

For simple regular expressions like this one, you can solve it by switching to borrow the regex engine from the JS host in js_sys::RegExp.

https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.RegExp.html

Here's a simple snippet that uses it.

```rust
use js_sys::RegExp;
#[wasm_bindgen].
pub fn regex_exec(input: &str) -> bool {
  let expr = RegExp::new(r"\w+", "u");
  expr.test(input)
}
```

**Comment by aqrln** [comment]
Thanks for opening the issue! Would you be up to opening a PR for this?

**Comment by mizchi** [comment]
thx @jkomyno @aqrln
