### ISSUE TITLE
what is openssl used for?

### ISSUE THREAD

**Issue by tmm1** [prisma/prisma-engines#5011]
and is there a way to use an alternative like rust-tls?

<img width="1424" alt="Screenshot 2024-10-02 at 11 51 04 AM" src="https://github.com/user-attachments/assets/0ceb2a82-ceac-469a-aaa7-5a88d2119581">

**Comment by aqrln** [comment]
Prisma uses TLS by default if it's enabled on the database side. Postgres driver (`tokio-postgres`) is configured to use the `native-tls` crate, which uses OpenSSL on Linux and most other systems except macOS and Windows where it uses the platform native Security.framework and SChannel respectively. It's possible to use https://crates.io/crates/tokio-postgres-rustls instead, so feel free to open a PR to add it and put it behind a cargo feature if it's important for you. I'd love if we used rustls by default, but that would certainly be a breaking change, and we'd need to understand how many of the users are relying on TLS versions or cipher suites not supported by rustls if we were to do that. Compatibility was a big problem when we briefly tried using rustls in the SQL Server connector.

**Comment by tmm1** [comment]
thanks for the pointer to [tokio-postgres-rustls](https://crates.io/crates/tokio-postgres-rustls). I'll give it a shot and open a PR if it works out for us

**Comment by tmm1** [comment]
calling this fixed with https://github.com/prisma/prisma-engines/pull/4998 merged
