### ISSUE TITLE
Introduce consistent version output amongst engines

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-engines#521]
The output of the version command is inconsistent right now:
```
./prisma --version
prisma HASH

./introspection-engine --version
HASH

./migration-engine --version
HASH
```

We should either always print the engine name or never. For the frontend use-cases not printing the engine name would be sufficient.

**Comment by dpetrick** [comment]
This is due to a mismatch in CLI tooling used in the different binaries. Unifying them to the standard we want to use would cause the prefix to be always printed. As this is low priority work I'll put it off for now until we're more at liberty to do small improvements like this.

**Comment by pimeys** [comment]
:3

**Comment by pimeys** [comment]
This is done.
