### ISSUE TITLE
Extend Benchmarking Suite

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#548]
Recently @pimeys did some initial benchmarking of the major the code changes related to the AUMFIDARR project. This yielded some first very good insights into the impact of those changes. I think we should invest more into this testing setup to also understand the following aspects:
* We should benchmark how the resolving of many to many relations changed. (the initial testing did not have a test for this imo)
* We should benchmark how the resolving of one to many relations behaves depending on which side of the relation is traversed. We have different slightly [code paths](https://github.com/prisma/prisma-engines/blob/e167d27e7f147151af1411efe20c1aa525059cb8/query-engine/core/src/interpreter/query_interpreters/nested_read.rs#L178) for each side. E.g. we should benchmark retrieving all posts for a given blog but we should also measure retrieving the related blog for a given post. (the original testing only executed one side imo)
* For all queries we should generally measure the impact on the CPU load of database and query engine. My expectation is that the database shows less CPU load with the new appraoch since we moved joining logic from the db to the query engine.
* We should benchmark the performance impact of pagination. Specifically we should not only measure top level pagination but also nested pagination as those have very different work profiles.

**Comment by pimeys** [comment]
- Do self-relations count? Such as:
``` prisma
model User {
  id Int @id
  friendWith User[] @relation("FriendShip")
  friendOf User[] @relation("FriendShip")}
```
- This should be easy.
- I don't really trust these measurements and I don't see a point of really measuring this. Yes, we do less cpu in the db, but what matters to our users is how fast we can query.
- This was removed due to us comparing ourselves to Hasura, which doesn't have nested pagination. We can add it back.

**Comment by pimeys** [comment]
New queries:

``` graphql
query ComplexRelationsFromOppositeSide {
  findManyComment(where: { id_lt: 100 }) {
    id
    content
    post {
      id
      content
      author {
        id
        firstName
        lastName
      }
    }
  }
}

query ManyToManyFromSideA {
  findManyUser(where: { id_lt: 100 }) {
    id
    firstName
    lastName
    friendWith { id firstName lastName }
  }
}

query ManyToManyFromSideB {
  findManyUser(where: { id_lt: 100 }) {
    id
    firstName
    lastName
    friendOf { id firstName lastName }
  }
}

query NestedPagination {
  findManyUser(first: 100) {
    id
    firstName
    lastName
    posts(skip: 5, orderBy: id_DESC) {
      id
      content
      comments(first: 3, orderBy: id_DESC) {
        id
        content
      }
    }
  }
}
```

**Comment by pimeys** [comment]
this is done.
