### ISSUE TITLE
ME: Composite relation keys not working with m2m

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-engines#566]
In a case with many-to-many relation, a composite key is giving a connector error if referencing multiple fields. Example:

``` prisma
model User {
  id                  Int       @id
  firstName           String
  lastName            String
  friendWith          User[]    @relation("Friendship", references: [firstName, lastName])
  @@unique([firstName, lastName])
}
```

**Comment by tomhoule** [comment]
![Screenshot from 2020-03-12 14-08-11](https://user-images.githubusercontent.com/13155277/76524812-05cfbc80-646b-11ea-992a-b693d09bae9c.png)
![Screenshot from 2020-03-12 14-08-31](https://user-images.githubusercontent.com/13155277/76524820-09fbda00-646b-11ea-9730-ee9d9e61b5e7.png)

**Comment by tomhoule** [comment]
cc @mavilein

**Comment by tomhoule** [comment]
Also cc @janpio  - this could be relevant to ongoing spec and product work.

**Comment by janpio** [comment]
It would be interesting to have the SQL version of what Julius posted, and see what Introspection does with it.

**Comment by tomhoule** [comment]
If you mean the SQL that results from migrating this with the ME, there is none because the ME can't migrate to this schema at the moment. What @pimeys  intended was probably similar to the join table I posted on slack (with or without an additional PK). I think it would be introspected to a separate model, but @do4gr  knows better.

**Comment by janpio** [comment]
Nah, what SQL someone could write all by themselves that we would later (after we implemented all this stuff) would be introspected as that model. So without any P2 involvement for now, just the _theoretical_ SQL for that model.

**Comment by tomhoule** [comment]
![Screenshot from 2020-03-19 16-16-11](https://user-images.githubusercontent.com/13155277/77082731-cc63f780-69fc-11ea-9ffb-3d5b57f67a23.png)

**Comment by janpio** [comment]
Adding some information here:

Trying to `migrate up` the model from https://github.com/prisma/prisma-engines/issues/566#issue-577789300 gives this:

https://prisma-errors.netlify.com/report/2290
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR 42000 (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') REFERENCES `_foo12`.`User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE' at line 1')
```

From migration `README`:
```sql
CREATE TABLE `_foo12`.`User` (
    `firstName` varchar(191) NOT NULL DEFAULT '' ,
    `id` int NOT NULL  ,
    `lastName` varchar(191) NOT NULL DEFAULT '' ,
    PRIMARY KEY (`id`)
) 
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci

CREATE UNIQUE INDEX `User.firstName_lastName` ON `_foo12`.`User`(`firstName`,`lastName`)

ALTER TABLE `_foo12`.`User` ADD FOREIGN KEY () REFERENCES `_foo12`.`User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE

DROP TABLE `_foo12`.`_migration`;
```

The FK indeed does not make sense.

What are next steps here then? Are we really suppose to have implicit m:n self relations?

**Comment by mavilein** [comment]
@janpio : Yes i think this should work. The example model you are referencing is 1:n relation though. It is not even m:n.

**Comment by janpio** [comment]
Good point, thanks for spotting that.

**Comment by dpetrick** [comment]
I am fairly confused about the issue. Multiple times in the past we explicitly stated that this is not behavior we want to implement, yet it seems like there has been a decision sometime somewhere that this is supposed to happen? Several code pieces in the core rely on the assumption that only IDs can be used in m:n, because that's the "Prisma style". Or am I completely missing something here?

**Comment by mavilein** [comment]
@dpetrick : I don't remember exactly like that. I thought of it as a temporary restriction. However it could make sense to keep it as is. This is one of our last opinionations and if users don't like it they can still escape through modeling this explicitly. 
I will add this as a point to a list of things we should discuss after the beta release.

**Comment by mavilein** [comment]
Internal Note: we will probably go with what @dpetrick suggested. Once the decision is final we will adapt the parser to disallow schemas like this.

**Comment by tomhoule** [comment]
We implemented this: M2M relations are always between models with a single id field now.
