### ISSUE TITLE
Proposal: Tighten datamodel parser rules for @relation

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma-engines#568]
The following datamodel should be rejected as invalid:
```prisma
model ModelA {
    b B @relation(references: [b_1, b_2])
}

model ModelB {
    b_1 Int @id
    b_2 String @unique
}
```

Reason: All SQL databases reject the foreign key either during creation or reject queries during runtime. All DBs we currently support require a constraint to span exactly the columns the FK is referencing.

**Comment by janpio** [comment]
Did I understand correctly:
Until now `@relation` would mainly refer to `@id` columns, thus a unique index of some kind always existed. Now with relations that can refer to no-`@id` fields, this is more complicated.

Interesting enough the example in the PSL specs would also be affected by what you write: https://github.com/prisma/specs/tree/master/schema#referencing-fields-that-are-not-id Correct?
