### ISSUE TITLE
EPIC: Prisma Core Primitive Types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#57]
**Spec**: The relevant part of the spec on the Prisma Schema Language can be found [here](https://github.com/prisma/specs/tree/master/schema#data-types).

**Description**: The PSL defines several core data types that must be implemented by each connector. We must make sure that we support exactly those not less or more.

**Example**:
The following example shows a `User` model where the combination of `firstName` and `lastName` is unique.
```graphql
model User {
  id        String @default(cuid())
  string String
  bool Boolean
  int Int
  float Float
  dateTime DateTime
}
```
## Links to actual Work Packages
* not created yet

**Comment by mavilein** [comment]
I asked for clarification [here](https://github.com/prisma/specs/issues/177).

**Comment by yoshuawuyts** [comment]
Notes from triage: this has been completed.
