### ISSUE TITLE
Guard-rail models with known unsupported identifier types in introspection

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#592]
From the type mappings testing I've been doing, we know some types won't work as model identifiers (unique or id), for example JSON or single-precision floats on MySQL, or won't work when writing (date, time, fixe-length strings). That second category is confusing because you _can_ create records, but they will fail to be read with the id you created them with. Should we guardrail those in introspection, when they are the only identifier for a model?

Internal: slack thread https://prisma-company.slack.com/archives/C4GCG53BP/p1584632923457200

**Comment by tomhoule** [comment]
Conservatively, we could guard-rail only the types that are absolutely not supported by the database as IDs. I could make a list of these. cc @janpio @do4gr

**Comment by yoshuawuyts** [comment]
Note from triage: this is very much an edge case, this is not something we can address. The solution would not be part of introspection.
