### ISSUE TITLE
prisma-fmt formatting regression 

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-engines#620]
Given the following schema:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id Int          @id
}

model Ok {
  id Int @id
}
```

By running the following command:

```sh
prisma-fmt format -s 2 < schema.prisma
```

https://github.com/prisma/prisma-engines/commit/6aa23a61c78a5418a0231347458d639aa337ec1d is able to gracefully format this to:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id
}

model Ok {
  id Int @id
}
```

However `prisma-fmt` today https://github.com/prisma/prisma-engines/commit/8814060fa684793b73d07dbfccd4b7777b3361ae yields this:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorCollection { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL", span: Span { start: 55, end: 74 } }] }', libs/datamodel/core/src/ast/reformat/mod.rs:10:19
```

It's an issue with: `env("DATABASE_URL")`. The formatter shouldn't try to resolve variables, it should just check the syntax.

Where this pops up IRL: https://github.com/prisma/vscode/issues/40

**Comment by Sytten** [comment]
Found the issue, pushing a fix
