### ISSUE TITLE
Cleanup of InternalDatamodel of Query Engine

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#677]
The `InternalDatamodel` now contains a bunch of unused or weird code. Let's go through the code and see what we can clean up.

**Comment by dpetrick** [comment]
Most cleanup is tied to m:n relations. We'll have to wait for the final implementation / product decisions before cleaning up.

**Comment by yoshuawuyts** [comment]
Note from triage: we intend to do this as we tackle other features, there's no need to keep this open as a specific issue.
