### ISSUE TITLE
Datamodel Parser: Native Types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#71]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/30) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by mavilein** [comment]
- `core`
    - [ ] feature flagging
    - [ ] remove hardcoding of datasource name from `lift.rs`
    - [ ] add validation for number of arguments
    - [ ] add validation for placement on correct field type
    - [ ] implement rendering
- `native-types` lib
    - [ ] finish definitions for MySQL
- `sql-datamodel-connector`
    - [ ] finish implementation of Postgres
    - [ ] add implementation for MySQL

**Comment by mavilein** [comment]
MSSQL and SQLite can be ignored for now. MSSQL is still in the works. SQLite maybe won't have any native type definitions.

**Comment by mavilein** [comment]
Overview of types we want to support in the beginning: https://www.notion.so/prismaio/Type-Mappings-for-Native-Types-e475a3ce7a434e419144fe2cbfc38e63

**Comment by divideby0** [comment]
Just a heads up, the linked Notion doc is not public:

![image](https://user-images.githubusercontent.com/530343/91884193-3ab71200-ec4b-11ea-8977-c92c22e3f7d1.png)

**Comment by janpio** [comment]
That is intentional @divideby0 while we develop this feature. When we are ready to talk about this in the open, we will also document the supported types of course.

**Comment by divideby0** [comment]
Noted, thank you. I've got about 5+ projects going between Prisma 1 and Prisma 2 so, if you're interested in some early-adopter feedback, I'd be happy to chat in the Prisma slack.
