### ISSUE TITLE
FreeBSD images to the CI builds

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-engines#711]
FreeBSD is a still quite popular and very useful server OS. It should be quite straightforward to include it as a build target, hopefully even cross-compiling with cargo as we do windows and darwin.

We already got one user wanting binaries https://github.com/prisma/prisma/issues/2288

Remember to build to a certain FreeBSD version, due to the binaries not usually compatible between major versions. I suggest targeting always the latest major RELEASE branches, which are currently versions 11 and 12.

**Comment by judehunter** [comment]
I would love to see this.
Cross compiling on windows by myself, while doable, seems a little convoluted and would be nice if it could be built automatically.

**Comment by yoshuawuyts** [comment]
Note from triage: we're running FreeBSD CI for version 12, which is the version we intend to support for now. Closing!
