### ISSUE TITLE
Migration Engine: Native Types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#72]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/30) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by tomhoule** [comment]
See PR description for https://github.com/prisma/prisma-engines/pull/1069

The creation of new columns and tables is covered — the next part will be diffing the types of existing columns. I expect that second part to be much harder. After https://github.com/prisma/prisma-engines/pull/1069, the query engine work is unblocked.

**Comment by tomhoule** [comment]
Next step, diffing, needs to be done in collaboration with the introspection engine, because a lot of the work will happen in sql-schema-describer. IE issue: https://github.com/prisma/prisma-engines/issues/74

**Comment by pimeys** [comment]
- [ ] Basic infra
- [ ] SQL Server
- [ ] PostgreSQL
- [ ] MySql

**Comment by pimeys** [comment]
https://github.com/prisma/prisma-engines/pull/1462

**Comment by tomhoule** [comment]
Candidating this for the remaining work: general polishing and mapping Float to doubles.

**Comment by albertoperdomo** [comment]
There is a specific issue for changing the default mapping for Float and for polishing. Closing this.
