### ISSUE TITLE
Datamodel parsing brokes since alpha.940

### ISSUE THREAD

**Issue by Devlin556** [prisma/prisma-engines#734]
Hi! I'm using datamodel parser in my `rust` app (as `cargo` package) for own schema validation and can't validate schema since 940 alpha. For any valid/invalid schema - I got an error:
![image](https://user-images.githubusercontent.com/16045765/81079029-aa183180-8ef7-11ea-9da4-f0395a1029bf.png)
What is it mean? How I can fix it?
I'm using this function to validate:
![image](https://user-images.githubusercontent.com/16045765/81079395-2e6ab480-8ef8-11ea-89e0-9f29512754f5.png)
Thanks.

**Comment by mavilein** [comment]
Can you provide the complete original schema please?

**Comment by Devlin556** [comment]
@mavilein 
I was using many schemas, but error is the same.
For example, I was using schema from Prisma2 Docs:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  email String  @unique
  id    Int     @default(autoincrement()) @id
  name  String?
  posts Post[]
}

model Post {
  authorId  Int?
  content   String?
  id        Int     @default(autoincrement()) @id
  published Boolean @default(false)
  title     String
  author    User?   @relation(fields: [authorId], references: [id])
}
```

And got the error:

![image](https://user-images.githubusercontent.com/16045765/81093445-cffb0180-8f0a-11ea-8f3b-6ed36988fa48.png)


But `alpha.939` validated this schema fine.

**Comment by mavilein** [comment]
@Devlin556 : Hmm this is validating fine for me in my vs code. In the screenshot above it looks like as if all of schema is a one line string. Is this the case? If yes this is the problem. We are requiring new lines by now.

**Comment by Devlin556** [comment]
@mavilein I noticed that I'm using escaped newline instead of a newline. I updated this and validating works fine. Thank you!
