### ISSUE TITLE
Introspection Engine: Native Types

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#74]
Check the related [epic](https://github.com/prisma/prisma-engine/issues/30) for an initial breakdown of work packages.

Please use supply a more detailed task list in a comment.

**Comment by do4gr** [comment]
The initial part got merged. 

Open topics: 
- infer precision on Postgres array types
- settling on argument data type for native types definitions (currently Vec<u32>, we might need custom enums there
)

**Comment by do4gr** [comment]
Postgres array precision is now done.
