### ISSUE TITLE
Prevent invalid models from being included in introspection / pass in DM parsing

### ISSUE THREAD

**Issue by dpetrick** [prisma/prisma-engines#761]
In a client issue (https://github.com/prisma/prisma-client-js/issues/670) it came up that introspection is allowing the following model and the datamodel parser is not rejecting the model as invalid:
```prisma
model poll_votes {
  created_at     DateTime
  poll_id        Int?
  poll_option_id Int?
  updated_at     DateTime
  user_id        Int?
  polls          polls?        @relation(fields: [poll_id], references: [id])
  poll_options   poll_options? @relation(fields: [poll_option_id], references: [id])
  users          users?        @relation(fields: [user_id], references: [id])

  @@index([poll_id], name: "index_poll_votes_on_poll_id")
  @@index([poll_option_id], name: "index_poll_votes_on_poll_option_id")
  @@index([user_id], name: "index_poll_votes_on_user_id")
  @@unique([poll_id, poll_option_id, user_id], name: "index_poll_votes_on_poll_id_and_poll_option_id_and_user_id")
}
```

The model above has no valid primary identifier, because the only part that might qualify is the unique (`@@unique`), but it contains nullable fields, resulting in the model not having a primary identifier, causing errors when querying the model in any way.

The introspection and the datamodel parser should follow the rule that the query-engine already has baked in as check during runtime to find the primary identifier of a model. A model has a valid identifier if:
- The model has an `@id` directive OR
- The model has an `@@id` directive OR
- The model has an `@unique` directive on a non-nullable field OR
- The model has an `@@unique` directive on only non-nullable fields.

**Comment by mavilein** [comment]
This was implemented a few weeks ago in the parser.
