### ISSUE TITLE
Introduce debugging mode to trigger panics in query engine

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma-engines#764]
After a conversation in Slack, @dpetrick had the following proposal to add the possibility to trigger panics for debugging:

- `--debug` to enable debug features below.
- Header `X-DEBUG-NON-FATAL` or similar to panic in the request thread and returns a panic for the request, but the QE is still alive
- Header `X-DEBUG-FATAL` or similar to let the QE die completely

Creating this so we can track this in the sprint.

**Comment by dpetrick** [comment]
Available on dev 16 onwards.
