### ISSUE TITLE
Create a migration engine <-> introspection engine test setup

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#808]
Migrating after introspecting, or re-introspecting a migrated database are both workflows that we currently do not test, and that we would like to make smooth and painless for our users. We know some users are also having issues with this. A first step towards tackling this would be a test setup with both migration and introspection engines so we can easily test various scenarios.

This can very easily live within the existing engines test suite, maybe as a separate test crate.

cc @do4gr

**Comment by Jolg42** [comment]
Related https://github.com/prisma/migrate/issues/481

**Comment by albertoperdomo** [comment]
Internal note: We are prioritizing the green-field workflow for now.

**Comment by yoshuawuyts** [comment]
Note from triage: we still want to do this, but it's not prioritized right now.

**Comment by yoshuawuyts** [comment]
Triage: no change

**Comment by tomhoule** [comment]
Candidating this for discussion:

- Do we need this additionally to introspection CI?
- If yes, when?

**Comment by albertoperdomo** [comment]
It seems this would involve a lot of effort, even for just writing the tests. Deferred.

**Comment by tomhoule** [comment]
We have migrations CI now, so this issue is not relevant anymore.
