### ISSUE TITLE
Discussion: Backwards-compatibility of migrations table/files contents

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#81]
We are approaching a point where we will need strong backwards compatibility of the persisted state of the migration engine.

To avoid breaking backwards compatibility of the migrations, we can write end to end tests that do:

- snapshot testing of RPC inputs/outputs (json)
- snapshot testing of migrations table (json?)

For the snapshots, we could use the [insta](https://crates.io/crates/insta) crate.

Every time a snapshot breaks, we must manually change the test suite so it tests with the new snapshot in addition to the old (ideally, this would just be adding a file name to a static list). That way, we test that old migrations keep producing the same results.

It's unambiguous that the contents of the migration table must be backwards-compatible, but I am less sure for RPC. We should probably isolate the results that get persisted to the migrations folder, since we can evolve the API in sync with the Lift CLI.

Related issue: https://github.com/prisma/lift/issues/151

@mavilein  @timsuchanek

**Comment by mavilein** [comment]
Backwards compatibility for the JSON RPC is currently not strictly required. The CLI uses a pinned version of the migration engine. In case we do a breaking change we would coordinate with @timsuchanek so he can adapt the CLI code. We would require less coordination though if we are backwards compatible. So let's strive for it but we do not need to be dogmatic about it.

**Comment by yoshuawuyts** [comment]
Notes from triage: things have changed since opening this issue so it no longer accurately captures intent.
