### ISSUE TITLE
CI should build binaries for FreeBSD 12

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma-engines#852]
Parent ticket: https://github.com/prisma/prisma/issues/2841

**Comment by pimeys** [comment]
https://github.com/wezm/freebsd-cross-build

**Comment by janpio** [comment]
Unfortunately we had to undo this as described in https://github.com/prisma/prisma/issues/3558: We do not build binaries for FreeBSD 12 and provide them for download automatically any more. Please see https://github.com/prisma/prisma-engines#building-prisma-engines and https://www.prisma.io/docs/understand-prisma/under-the-hood#using-custom-engine-binaries how to build and then use a custom binary.
