### ISSUE TITLE
[Introspection] Comment out Models that do not have a strict unique criteria

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#858]
I tightened the validation of models and their unique criterias. A unique criteria that spans optional fields is not enough anymore for a model to be valid. We should adapt the introspection accordinly to comment out those models.

[Diff from introspection CI](https://github.com/prisma/introspection-engine-output/commit/6168e39a0271b935e66740b6d79d991832994b51)

**Comment by do4gr** [comment]
This is now implemented.
