### ISSUE TITLE
Ambiguous self relation detected

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma-engines#87]
Hello I think I found a bug.

![image](https://user-images.githubusercontent.com/7302317/61594734-8184ac80-abef-11e9-9c24-c50fe71b05a4.png)
![image](https://user-images.githubusercontent.com/7302317/61594739-8b0e1480-abef-11e9-8011-2f000989596d.png)

**Comment by janpio** [comment]
(This spawned an issue by @schickling in `specs`: https://github.com/prisma/specs/issues/213)

**Comment by jasonkuhrt** [comment]
I just hit this issue tonight and Google'd my way here.

```prisma
model User {
  id       String @id @default(cuid())
  mother   User?
  father   User?
  children User[]
}
```

I expected this to just work. Naively maybe :)

**Comment by yoshuawuyts** [comment]
Talked about this in triage today, this should be fixed.
