### ISSUE TITLE
Rust cuid() implementation may output more than 25 characters

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-engines#878]
**Problem**

We have someone trying to migrate to Prisma 2 right now. In the Prisma 1 => Prisma 2 upgrade, we retain the `varchar(25)` data type for IDs. 

It appears that cuid()'s can return more than 25 characters [according to the creator of cuid](https://github.com/ericelliott/cuid/issues/164#issuecomment-516637547).

**Hypothesis**

It doesn't make a lot of sense why this wasn't caught in Prisma 1. My guess is that the Scala implementation of `cuid()` will always return 25 characters (probably a bug), while the Rust implementation may return more than 25 characters (according to spec).

**How to Test**

1. Run the Rust cuid() implementation in a loop to see if you can generate more than 25 characters.
2. Double-check the Scala implementation to see if it's limited to 25 characters.

Issue: https://github.com/prisma/upgrade/issues/34#issuecomment-653246589

**Comment by janpio** [comment]
Length of 26 for generated ID confirmed: https://github.com/prisma/upgrade/issues/34#issuecomment-653415020
