### ISSUE TITLE
Create CONTRIBUTING.MD

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#890]
What should go in here?

**Comment by yoshuawuyts** [comment]
It depends on what we want from this.

- This is what I usually use: https://github.com/yoshuawuyts/rust-lib-template/blob/master/.github/CONTRIBUTING.md
- Here's another good one (and I should probably incorporate this text into my own version): https://github.com/peermaps/eyros/blob/master/CONTRIBUTING

In addition to that we could probably add another section: "external contributions":

```markdown
## External Contributions

Most of the development of Prisma Engines is done by employees of Prisma. We welcome external
contributions, but need to balance that with the direction set in our company roadmap. Before
attempting to implement any large feature we recommend chatting with us first through Slack,
or opening an issue first.
```

**Comment by janpio** [comment]
I think right now the "External Contributions" part is the most pressing one, as we should manage expectations there.

**Comment by mavilein** [comment]
This was done in https://github.com/prisma/prisma-engines/pull/995
