### ISSUE TITLE
Transaction is a problematic reserved word

### ISSUE THREAD

**Issue by defrex** [prisma/prisma-engines#892]
I just upgraded from `2.1.3` to `2.2.0` and am now being told `Transaction` can't be a model name.

I do, of course, understand that a database transaction is a thing, but does that need to mean I can't name a model `Transaction`?

A Transaction is an important entity when modeling financial systems, and it doesn't have a great analog word.

**Comment by mavilein** [comment]
Yes this means you can't name a model `Transaction`. The reason is that we recently introduced the transaction API which is exposed as `prisma.transaction`. The operations for the model `Transaction` would live in the same namespace.
Do you maybe have an idea how we should solve this differently?

**Comment by defrex** [comment]
You could put the transaction support into its own namespace. For example,

```js
import { PrismaClient, transaction } from '@prisma/client'
```

Hanging all future APIs off the same namespace as the models seems problematic to me. Reserving `Transaction` is frustrating to me (and likely others working on fintech), and I suspect you'll find similar frustration if you need to ban other model names in the future. Especially once users have had more time to build on top of Prisma 2.

Personally, I'm trying to migrate from TypeORM to Prisma 2. Not being able to map the model names across that migration is going to make it way more painful and confusing, so much so that I may have to abandon the move. That's really disappointing since Prisma 2 seems like the ORM JavaScript needs.

**Comment by matthewmueller** [comment]
This is a great point @defrex. In addition to `transaction`, everytime we add a new feature we may break people.

Some possibilities

### Solution A: Separate Namespace

```ts
import { PrismaClient, transaction } from '@prisma/client'

await transaction([
  prisma.transaction.findOne(...), 
  prisma.user.updateMany(...), 
])
```


- Pros:
  - Unlikely to cause issues
  - Clean API

- Cons:
  - Does this work? How does transaction interact with Prisma?
  - Hidden, can't autocomplete to find this easily

### Solution B: Reserve $ for future commands like this

```js
prisma.$transaction(...)
```

- Pros:
  - Unlikely to cause issues

- Cons:
  - Sort of ugly

### Solution C: Use verbs

```js
prisma.begin(...)
```

- Pros:
  - Most "beautiful"

- Cons:
  - May cause conflicts in the future

**Comment by defrex** [comment]
My preference here would be Solution A, though B and D also seem reasonable to me. However, looking over [the current docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/transactions#bulk-operations-experimental), I suspect the API will be a little limiting relative to what I'd like to do with database transactions.

For example, it's common in some frameworks (Rails, Django, etc.) to wrap the entire request/response cycle in a single transaction. This means establishing some kind of "transaction context" that can be passed around and added to over time.

I also note there is a race condition in this example (unless I'm missing something) if the promises resolve on their own before being added to the transaction.

```typescript
const write1 = prisma.user.create()
const write2 = prisma.orders.create()
const write3 = prisma.invoices.create()

await somethingSlow()

await prisma.transaction([write1, write2, write3])
```

Here is a sketch of something that could address those issues.

```typescript
import { PrismaClient, Transaction } from '@prisma/client'

const prisma = new PrismaClient()
const transaction = new Transaction()

await prisma.user.fineOne({
  where: { id },
  transaction,
})

await prisma.posts.findMany({
  where: { userId: user.id },
  transaction,
})
```

**Comment by yoshuawuyts** [comment]
Triage: this is being discussed by product

**Comment by defrex** [comment]
Looks like you're gone with the `prisma.$transaction` solution in 2.4. 🎉 

I tested it and it solves my issues. 🙏
