### ISSUE TITLE
Add tests using Yugabyte DB

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#901]
Yugabyte DB indicates it is wire protocol compatible with PostgreSQL: https://docs.yugabyte.com/latest/api/ysql/

As some users see this as an indicator it can also be used with Prisma, we should test this and document our result in the documentation.

This would include adding a dockerized version of this database to our test matrix.

**Comment by yoshuawuyts** [comment]
Triage: the target outcome here is to find out whether it passes our test suite.

**Comment by yoshuawuyts** [comment]
This has been completed in: https://github.com/prisma/prisma-engines/pull/1139 -- unfortunately Yugabyte isn't compatible with our Postgres adapter.
