### ISSUE TITLE
Query Engine: Automated Benchmarks

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#92]
This is a followup task from this [issue](https://github.com/prisma/prisma-engine/issues/76).

Idea: We should instrument prisma server to measure every single request and have a prometheus/grafana setup for better timescale graphs.

**Comment by pimeys** [comment]
Idea:

- First we create the benchmark tool (under construction now) https://github.com/prisma/chihiro
- Then we store data to ElasticSearch and visualize with Kibana
- We must start versioning Prisma from now on
- After a release a Buildkite build starts running the benchmarks, storing to Elastic Cloud
- We must have a prisma server and a psql server running somewhere and we must update it to the latest version after a release.

Working on the benchmarking and storing part now.

**Comment by pimeys** [comment]
We are currently waiting for dedicated servers from Hetzner. Will be available either this week or early next week.

Meanwhile I planned to write an article how to benchmark your code for Query Engine.

**Comment by divyenduz** [comment]
Internal note: dropping from this sprint

**Comment by yoshuawuyts** [comment]
Note from triage: this has been done!
