### ISSUE TITLE
Design and implement observability

### ISSUE THREAD

**Issue by yoshuawuyts** [prisma/prisma-engines#933]
When dealing with performance issues in the past we've primarily relied on black-box testing of the engines. In order to be able to more clearly understand where we're spending our time we should design and implement a strategy around observability.

**Comment by yoshuawuyts** [comment]
First PR in the series is: https://github.com/http-rs/http-types/pull/203 -- this enables us to operate on `Server-Timing` headers. Step after that is to integrate it into Tide and use it to capture + serialize `tracing` timings. This will provide us with the ability to inspect per-query engine timings on the graphql playground.

**Comment by yoshuawuyts** [comment]
PR to add Server-Timing headers to engines for the playground only: https://github.com/prisma/prisma-engines/pull/1003

**Comment by garrensmith** [comment]
closing this since it is now implemented.
