### ISSUE TITLE
CI should build binaries for FreeBSD 11

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#934]
Follow up issue to https://github.com/prisma/prisma-engines/issues/852 which could unfortunately only build binaries for FreeBSD 12.

Parent issue: https://github.com/prisma/prisma/issues/3091

**Comment by yoshuawuyts** [comment]
Triage: @dpetrick has investigated this and we're missing a FreeBSD 11 base image. This is a great issue for someone in the community to pick up.

**Comment by janpio** [comment]
Unfortunately we had to undo this as described in https://github.com/prisma/prisma/issues/3558: We do not build binaries for FreeBSD 12 and provide them for download automatically any more. Please see https://github.com/prisma/prisma-engines#building-prisma-engines and https://www.prisma.io/docs/understand-prisma/under-the-hood#using-custom-engine-binaries how to build and then use a custom binary.
