### ISSUE TITLE
Query Engine: Run Benchmarks continuously

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma-engines#95]
This is a followup task from this [issue](https://github.com/prisma/prisma-engine/issues/76).

We should run our new benchmarks on a continuous basis. Either daily or on each commit etc...

**Comment by pimeys** [comment]
This should also have metrics included in the prisma codebase, at least counters and histograms, and a prometheus endpoint.

**Comment by yoshuawuyts** [comment]
This has been done!
