### ISSUE TITLE
MySQL case sensitivity issue in ME on windows

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#950]
MySQL is case-insensitive on Windows. All identifiers are internally lower-cased. The migration engine diffing logic cannot handle this at the moment.

Links:
- https://github.com/prisma/migrate/issues/525
- https://github.com/prisma/migrate/issues/339
- https://github.com/prisma/migrate/issues/373
- https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

**Comment by tomhoule** [comment]
Update on this: there is an internal document describing the issue and potential solutions, now gathering feedback.

**Comment by tomhoule** [comment]
Candidating this with the intent of trying a SqlSchemaCalculator level fix. This should make implementation easier, but testing is still an open challenge.

**Comment by albertoperdomo** [comment]
We will continue monitoring this sprint, possibly close after if there are no big issues.

**Comment by tomhoule** [comment]
We have enough user feedback to be comfortable closing this issue now. What a ride.
