### ISSUE TITLE
Validate constraint/index name limits on MySQL and PostgreSQL in the schema parser

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma-engines#962]
We know the length limit for constraint/index names, and what the names we generate would be, so we should enforce it.

_To be expanded_.

**Comment by tomhoule** [comment]
Concrete issue for postgres: https://github.com/prisma/migrate/issues/542

**Comment by tomhoule** [comment]
This is related to the constraint names proposal.

**Comment by do4gr** [comment]
We will do this as part of the going GA cleanup when we remove the legacy codepaths. For the previewFlagged codepath this is already done in the parser.

**Comment by tomhoule** [comment]
We already do that
