### ISSUE TITLE
Switch GH Actions trigger from `repository_dispatch` to `workflow_dispatch` to enable running branches

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-engines#977]
This is the newer Event for GH: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
That would then just get the current branch or commit name as ref param to trigger the "Build Windows" workflow with the workflow configuration from the branch.
You also need to add that event to the `on:` in the yaml, but that should already be it.

A bit effort is that it requires the workflow_id as a param on the API: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
Not sure if that is really dynamic, but here is a GH Action in Typescript that shows it is quite straigtforward to get the ID and then use it: https://github.com/benc-uk/workflow-dispatch/blob/7ff1caf33291d1ed4001bebfa7342d5ad77eb3bf/src/main.ts#L24-L46

**Comment by carmenberndt** [comment]
> A bit effort is that it requires the workflow_id as a param on the API: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event

 The workflow_id is not needed, it can be replaced with the workflow file name.

**Comment by pantharshit00** [comment]
It is quite easy to do, I did it for out stale action here:

https://github.com/prisma/prisma/blob/7d36455d7304ad7b998c9e314c063aed965732e0/.github/workflows/label-stale-issues.yml#L5

**Comment by janpio** [comment]
Tool that sends the request is: https://github.com/prisma/engineer
Code for the GH component is here: https://github.com/prisma/engineer/tree/master/src/github
This is the current `repository_dispatch` trigger we want to replace: https://github.com/prisma/engineer/blob/6d59ac2018b16a5bcb1eda234d741ad51ccf43ad/src/release/gh_actions.rs#L81

**Comment by mavilein** [comment]
implemented in:
https://github.com/prisma/prisma-engines/pull/1008
https://github.com/prisma/engineer/pull/15
